-- Seed builtin agents from TOML files
-- Generated by build.rs

DELETE FROM agents WHERE display_name = 'ArgusWing';
INSERT INTO agents (display_name, description, version, provider_id, system_prompt, tool_names) VALUES ('ArgusWing', 'Default assistant for ArgusWing', '0.1.0', NULL, 'You are ArgusWing, a helpful AI assistant.', '["shell","read","grep","glob"]');
