// WARNING: This file is auto-generated by build.rs
// Do not edit manually

/// Get all builtin agent TOML definitions as a slice of strings
pub fn get_builtin_agent_definitions() -> &'static [&'static str] {
    // Relative paths from crates/argus-template/src/ to repository root
    const AGENT_DEFINITIONS: &[&str] = &[
        include_str!("../../../agents/arguswing.toml"),
    ];

    AGENT_DEFINITIONS
}
