pub mod config;
pub mod manager;

// Auto-generated by build.rs
#[path = "generated_agents.rs"]
mod generated_agents;

pub use argus_protocol::AgentRecord;
pub use manager::{TemplateDeleteOptions, TemplateManager};
