//! Argus Turn - single turn execution with LLM and tool support.
//!
//! This crate provides the core turn execution logic for agent-based conversations.
//! A "Turn" represents a single execution cycle: LLM → Tool → LLM (with parallel tool support).
//!
//! # Architecture
//!
//! The crate has been refactored to use a structural design pattern:
//!
//! - **`Turn`** (new): Owns its resources (tools, hooks) and is responsible only for execution
//! - **`TurnBuilder`**: Auto-generated by `derive_builder` for constructing Turn instances
//! - **`execute_turn()`** (legacy): Backward-compatible wrapper that internally uses `Turn`
//!
//! # Example (New API)
//!
//! ```ignore
//! use argus_turn::{Turn, TurnBuilder};
//! use argus_protocol::llm::ChatMessage;
//! use argus_protocol::tool::NamedTool;
//! use std::sync::Arc;
//!
//! let turn = TurnBuilder::default()
//!     .turn_number(1)
//!     .thread_id("thread-123".to_string())
//!     .messages(vec![ChatMessage::user("Hello!")])
//!     .provider(provider)
//!     .tools(vec![Arc::new(my_tool)])
//!     .hooks(vec![Arc::new(my_hook)])
//!     .config(TurnConfig::default())
//!     .stream_tx(stream_tx)
//!     .thread_event_tx(thread_event_tx)
//!     .build()?;
//!
//! let output = turn.execute().await?;
//! ```
//!
//! # Example (Legacy API - Still Supported)
//!
//! ```ignore
//! use argus_turn::{TurnInput, TurnInputBuilder, TurnOutput, execute_turn};
//! use argus_protocol::llm::ChatMessage;
//!
//! let input = TurnInputBuilder::new()
//!     .provider(my_provider)
//!     .messages(vec![ChatMessage::user("Hello!")])
//!     .build()
//!     .unwrap();
//!
//! let output = execute_turn(input, TurnConfig::default()).await.unwrap();
//! ```

pub mod config;
pub mod error;
pub mod execution;
pub mod turn;

pub use config::{
    TurnConfig, TurnConfigBuilder, TurnInput, TurnInputBuilder, TurnOutput, TurnOutputBuilder,
    TurnStreamEvent,
};
pub use error::TurnError;
pub use execution::{ExecutionMode, execute_turn, execute_turn_streaming};
pub use turn::{Turn, TurnBuilder};

// Re-export hook types from argus-protocol for convenience
pub use argus_protocol::{
    BeforeCallLLMContext, BeforeCallLLMResult, HookAction, HookEvent, HookHandler, HookRegistry,
    ToolHookContext,
};
