//! Turn struct for managing turn lifecycle and execution.
//!
//! This module defines the `Turn` struct, which owns its resources (tools and hooks)
//! and is responsible only for execution logic. Construction is handled by `TurnBuilder`
//! (auto-generated by `derive_builder`) or by the Thread layer.

use std::sync::Arc;

use derive_builder::Builder;
use futures_util::{StreamExt, future::join_all};
use tokio::sync::broadcast;
use tokio::time::{error::Elapsed, timeout};
use tracing;

use argus_protocol::llm::{
    ChatMessage, FinishReason, LlmProvider, LlmStreamEvent, ToolCall, ToolCompletionRequest,
    ToolCompletionResponse, ToolDefinition,
};
use argus_protocol::tool::NamedTool;
use argus_protocol::{
    BeforeCallLLMContext, HookAction, HookContext, HookEvent, HookHandler, ThreadEvent, TokenUsage,
    ToolHookContext,
};

use super::{TurnConfig, TurnError, TurnOutput, TurnStreamEvent};

/// Turn identifier generator (simple counter for now).
fn generate_turn_id(thread_id: &str, turn_number: u32) -> String {
    format!("{}-turn-{}", thread_id, turn_number)
}

/// Result of processing an LLM response's finish_reason.
enum NextAction {
    /// Turn is complete, return the output.
    Return(TurnOutput),
    /// Continue with tool execution.
    ContinueWithTools {
        tool_calls: Vec<ToolCall>,
        #[allow(dead_code)]
        content: Option<String>,
    },
    /// Context length exceeded.
    LengthExceeded,
}

/// Result of a tool execution.
struct ToolExecutionResult {
    tool_call_id: String,
    name: String,
    content: String,
}

/// Accumulates streaming events into a complete response.
struct StreamingAccumulator {
    content: String,
    reasoning_content: String,
    tool_calls: Vec<(Option<String>, Option<String>, String)>,
    input_tokens: u32,
    output_tokens: u32,
    finish_reason: FinishReason,
}

impl StreamingAccumulator {
    fn new() -> Self {
        Self {
            content: String::new(),
            reasoning_content: String::new(),
            tool_calls: Vec::new(),
            input_tokens: 0,
            output_tokens: 0,
            finish_reason: FinishReason::Stop,
        }
    }

    fn process(&mut self, event: LlmStreamEvent) {
        match event {
            LlmStreamEvent::ReasoningDelta { delta } => {
                self.reasoning_content.push_str(&delta);
            }
            LlmStreamEvent::ContentDelta { delta } => {
                self.content.push_str(&delta);
            }
            LlmStreamEvent::ToolCallDelta(tc) => {
                // Ensure we have enough slots
                while self.tool_calls.len() <= tc.index {
                    self.tool_calls.push((None, None, String::new()));
                }
                if let Some(id) = tc.id {
                    self.tool_calls[tc.index].0 = Some(id);
                }
                if let Some(name) = tc.name {
                    self.tool_calls[tc.index].1 = Some(name);
                }
                if let Some(args_delta) = tc.arguments_delta {
                    self.tool_calls[tc.index].2.push_str(&args_delta);
                }
            }
            LlmStreamEvent::Usage {
                input_tokens,
                output_tokens,
            } => {
                self.input_tokens = input_tokens;
                self.output_tokens = output_tokens;
            }
            LlmStreamEvent::Finished { finish_reason } => {
                self.finish_reason = finish_reason;
            }
        }
    }

    fn into_response(self) -> ToolCompletionResponse {
        // Convert accumulated tool calls to ToolCall structs
        let tool_calls: Vec<ToolCall> = self
            .tool_calls
            .into_iter()
            .filter_map(|(id, name, args)| {
                Some(ToolCall {
                    id: id?,
                    name: name?,
                    arguments: serde_json::from_str(&args).unwrap_or(serde_json::Value::Null),
                })
            })
            .collect();

        ToolCompletionResponse {
            content: if self.content.is_empty() {
                None
            } else {
                Some(self.content)
            },
            reasoning_content: if self.reasoning_content.is_empty() {
                None
            } else {
                Some(self.reasoning_content)
            },
            tool_calls,
            input_tokens: self.input_tokens,
            output_tokens: self.output_tokens,
            finish_reason: self.finish_reason,
            cache_read_input_tokens: 0,
            cache_creation_input_tokens: 0,
        }
    }
}

/// A Turn represents a single execution cycle in a conversation.
///
/// The Turn owns its resources (tools and hooks) directly and is responsible
/// only for execution logic. Construction is handled by `TurnBuilder` or the Thread layer.
///
/// # Lifecycle
///
/// 1. **Construction**: Built via `TurnBuilder` with all required fields
/// 2. **Execution**: Call `.execute()` to run the turn (consumes self)
/// 3. **Completion**: Returns `TurnOutput` with updated messages and token usage
///
/// # Example
///
/// ```ignore
/// use argus_turn::{Turn, TurnBuilder};
/// use argus_protocol::llm::ChatMessage;
///
/// let turn = TurnBuilder::new()
///     .turn_number(1)
///     .thread_id("thread-123".to_string())
///     .messages(vec![ChatMessage::user("Hello!")])
///     .provider(provider)
///     .tools(vec![Arc::new(my_tool)])
///     .hooks(vec![Arc::new(my_hook)])
///     .config(TurnConfig::default())
///     .stream_tx(stream_tx)
///     .thread_event_tx(thread_event_tx)
///     .build()?;
///
/// let output = turn.execute().await?;
/// ```
#[derive(Builder)]
#[builder(pattern = "owned", build_fn(error = "TurnError"), name = "TurnBuilder")]
pub struct Turn {
    /// Turn identifier (auto-generated from thread_id and turn_number).
    #[builder(
        default = "generate_turn_id(self.thread_id.as_ref().unwrap_or(&\"unknown\".to_string()), *self.turn_number.as_ref().unwrap_or(&0))"
    )]
    pub id: String,

    /// Turn number (sequence in the thread).
    #[builder(setter(custom))]
    turn_number: u32,

    /// Thread identifier.
    #[builder(setter(custom))]
    thread_id: String,

    /// Message history for this turn.
    messages: Vec<ChatMessage>,

    /// LLM provider for completion requests.
    provider: Arc<dyn LlmProvider>,

    /// Tools available for this turn (direct ownership, no ToolManager needed).
    #[builder(default)]
    tools: Vec<Arc<dyn NamedTool>>,

    /// Hooks for lifecycle events (direct ownership, no HookRegistry needed).
    #[builder(default)]
    hooks: Vec<Arc<dyn HookHandler>>,

    /// Turn execution configuration.
    #[builder(default)]
    config: TurnConfig,

    /// Internal stream event sender.
    stream_tx: broadcast::Sender<TurnStreamEvent>,

    /// Thread event sender for broadcasting to subscribers.
    thread_event_tx: broadcast::Sender<ThreadEvent>,

    /// Event forwarder task handle (cleaned up on drop).
    #[builder(default)]
    _forwarder_handle: Option<tokio::task::JoinHandle<()>>,
}

impl TurnBuilder {
    /// Set turn number.
    pub fn turn_number(mut self, value: u32) -> Self {
        self.turn_number = Some(value);
        self
    }

    /// Set thread ID.
    pub fn thread_id(mut self, value: String) -> Self {
        self.thread_id = Some(value);
        self
    }
}

impl std::fmt::Debug for Turn {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Turn")
            .field("id", &self.id)
            .field("turn_number", &self.turn_number)
            .field("thread_id", &self.thread_id)
            .field("messages", &self.messages.len())
            .field("provider", &self.provider.model_name())
            .field("tools", &self.tools.len())
            .field("hooks", &self.hooks.len())
            .field("config", &self.config)
            .finish()
    }
}

impl Turn {
    /// Execute the turn and return the output.
    ///
    /// This method:
    /// 1. Spawns the event forwarder task
    /// 2. Executes the main LLM → Tool → LLM loop
    /// 3. Sends TurnCompleted/TurnFailed event
    /// 4. Sends Idle event
    /// 5. Returns TurnOutput with updated messages and token usage
    ///
    /// # Errors
    ///
    /// Returns `TurnError` for:
    /// - LLM failures
    /// - Tool execution failures
    /// - Hook blocks
    /// - Max iterations exceeded
    pub async fn execute(mut self) -> Result<TurnOutput, TurnError> {
        // Spawn event forwarder
        self.spawn_event_forwarder();

        // Execute main loop
        let result = self.execute_loop().await;

        // Send completion event
        match &result {
            Ok(output) => {
                let _ = self.thread_event_tx.send(ThreadEvent::TurnCompleted {
                    thread_id: self.thread_id.clone(),
                    turn_number: self.turn_number,
                    token_usage: output.token_usage.clone(),
                });
            }
            Err(error) => {
                let _ = self.thread_event_tx.send(ThreadEvent::TurnFailed {
                    thread_id: self.thread_id.clone(),
                    turn_number: self.turn_number,
                    error: error.to_string(),
                });
            }
        }

        // Send Idle event
        let _ = self.thread_event_tx.send(ThreadEvent::Idle {
            thread_id: self.thread_id.clone(),
        });

        result
    }

    /// Internal method: spawn event forwarder task.
    ///
    /// Forwards TurnStreamEvent to ThreadEvent for external subscribers.
    fn spawn_event_forwarder(&mut self) {
        let mut stream_rx = self.stream_tx.subscribe();
        let thread_event_tx = self.thread_event_tx.clone();
        let thread_id = self.thread_id.clone();
        let turn_number = self.turn_number;

        let handle = tokio::spawn(async move {
            while let Ok(event) = stream_rx.recv().await {
                match event {
                    TurnStreamEvent::LlmEvent(llm_event) => {
                        let _ = thread_event_tx.send(ThreadEvent::Processing {
                            thread_id: thread_id.clone(),
                            turn_number,
                            event: llm_event,
                        });
                    }
                    TurnStreamEvent::ToolStarted {
                        tool_call_id,
                        tool_name,
                        arguments,
                    } => {
                        let _ = thread_event_tx.send(ThreadEvent::ToolStarted {
                            thread_id: thread_id.clone(),
                            turn_number,
                            tool_call_id,
                            tool_name,
                            arguments,
                        });
                    }
                    TurnStreamEvent::ToolCompleted {
                        tool_call_id,
                        tool_name,
                        result,
                    } => {
                        let _ = thread_event_tx.send(ThreadEvent::ToolCompleted {
                            thread_id: thread_id.clone(),
                            turn_number,
                            tool_call_id,
                            tool_name,
                            result,
                        });
                    }
                }
            }
        });

        self._forwarder_handle = Some(handle);
    }

    /// Internal method: trigger hooks and return the action.
    ///
    /// Directly iterates over `self.hooks` (no HookRegistry needed).
    #[allow(dead_code)]
    async fn fire_hooks(
        &self,
        event: HookEvent,
        ctx: &HookContext,
    ) -> Result<HookAction, TurnError> {
        for hook in &self.hooks {
            let action = match event {
                HookEvent::BeforeCallLLM => {
                    let HookContext::BeforeCallLLM(ctx_any) = ctx else {
                        return Err(TurnError::LlmCallBlocked {
                            reason: "Invalid hook context".to_string(),
                        });
                    };
                    hook.on_before_call_llm(ctx_any).await
                }
                HookEvent::BeforeToolCall | HookEvent::AfterToolCall | HookEvent::TurnEnd => {
                    let HookContext::ToolEvent(ctx_any) = ctx else {
                        return Err(TurnError::ToolCallBlocked {
                            reason: "Invalid hook context".to_string(),
                        });
                    };
                    hook.on_tool_event(ctx_any).await
                }
            };

            // Handle blocking actions
            if let HookAction::Block(reason) = action {
                return Ok(HookAction::Block(reason));
            }

            // For modification actions (only BeforeCallLLM), return them
            if !matches!(action, HookAction::Continue) {
                return Ok(action);
            }
        }

        Ok(HookAction::Continue)
    }

    /// Internal method: execute the main LLM → Tool → LLM loop.
    ///
    /// This is where the core execution logic lives.
    #[allow(dead_code)]
    async fn execute_loop(&mut self) -> Result<TurnOutput, TurnError> {
        let mut messages = std::mem::take(&mut self.messages);
        let max_iterations = self.config.max_iterations.unwrap_or(50);
        let tool_timeout_secs = self.config.tool_timeout_secs.unwrap_or(120);
        let mut token_usage = TokenUsage::default();

        // Add system message about max_tool_calls ONCE before loop (not inside to avoid accumulation)
        let max_tool_calls = self.config.max_tool_calls;
        if let Some(max) = max_tool_calls
            && !self.tools.is_empty()
        {
            let system_content = format!(
                "IMPORTANT: You can only call at most {} tool(s) per response. \
                If you need to call multiple tools, please proceed step by step - \
                call tools one at a time and wait for the results before calling the next tool.",
                max
            );
            messages.insert(0, ChatMessage::system(system_content));
        }

        for iteration in 0..max_iterations {
            // Prepare tools from self.tools
            let tools: Vec<ToolDefinition> = self.tools.iter().map(|t| t.definition()).collect();

            // Fire BeforeCallLLM hook (can modify messages/tools or block)
            let ctx = BeforeCallLLMContext {
                messages: messages.clone(),
                tools: tools.clone(),
                iteration,
            };
            match self
                .fire_hooks(HookEvent::BeforeCallLLM, &HookContext::BeforeCallLLM(ctx))
                .await?
            {
                HookAction::Continue => {}
                HookAction::ModifyMessages(modified_messages) => {
                    messages = modified_messages;
                }
                HookAction::ModifyTools(_modified_tools) => {
                    // Tools are re-built from definitions, so we can't easily modify them here
                    // For now, just log a warning
                    tracing::warn!("Hook attempted to modify tools, but this is not yet supported");
                }
                HookAction::Modify {
                    messages: modified_messages,
                    tools: _,
                } => {
                    messages = modified_messages;
                }
                HookAction::Block(reason) => {
                    return Err(TurnError::LlmCallBlocked { reason });
                }
            }

            // Build the request with current messages and tools
            let request = ToolCompletionRequest::new(messages.clone(), tools.clone());

            // Call the LLM (streaming mode is always enabled in Turn)
            let response = self.call_llm_streaming(request).await?;

            // Process response
            match self.process_finish_reason(response, &mut messages, &mut token_usage)? {
                NextAction::Return(output) => {
                    // Fire TurnEnd hook
                    let ctx = ToolHookContext {
                        event: HookEvent::TurnEnd,
                        tool_name: String::new(),
                        tool_call_id: String::new(),
                        tool_input: serde_json::Value::Null,
                        tool_result: None,
                        error: None,
                        tool_manager: None,
                        thread_event_sender: Some(self.thread_event_tx.clone()),
                        thread_id: Some(self.thread_id.clone()),
                        turn_number: Some(self.turn_number),
                    };
                    // TurnEnd is observe-only, ignore errors
                    let _ = self
                        .fire_hooks(HookEvent::TurnEnd, &HookContext::ToolEvent(ctx))
                        .await;

                    return Ok(output);
                }
                NextAction::ContinueWithTools { tool_calls, .. } => {
                    // Execute tools in parallel
                    let tool_results = self
                        .execute_tools_parallel(tool_calls, tool_timeout_secs)
                        .await;

                    // Add tool result messages to history
                    for result in tool_results {
                        messages.push(ChatMessage::tool_result(
                            result.tool_call_id,
                            result.name,
                            result.content,
                        ));
                    }

                    // Continue the loop with updated messages
                }
                NextAction::LengthExceeded => {
                    return Err(TurnError::ContextLengthExceeded(
                        (token_usage.input_tokens + token_usage.output_tokens) as usize,
                    ));
                }
            }
        }

        // Max iterations reached
        Err(TurnError::MaxIterationsReached(max_iterations))
    }

    /// Calls the LLM in streaming mode, accumulating the response.
    ///
    /// Falls back to non-streaming if the provider doesn't support streaming.
    async fn call_llm_streaming(
        &self,
        request: ToolCompletionRequest,
    ) -> Result<ToolCompletionResponse, TurnError> {
        match self
            .provider
            .stream_complete_with_tools(request.clone())
            .await
        {
            Ok(mut stream) => {
                let mut accumulator = StreamingAccumulator::new();
                while let Some(event_result) = stream.next().await {
                    let event = event_result.map_err(TurnError::LlmFailed)?;
                    // Forward to stream_tx
                    let _ = self
                        .stream_tx
                        .send(TurnStreamEvent::LlmEvent(event.clone()));
                    accumulator.process(event);
                }
                Ok(accumulator.into_response())
            }
            Err(argus_protocol::llm::LlmError::UnsupportedCapability { .. }) => {
                // Fallback to non-streaming
                tracing::debug!("Provider doesn't support streaming, using non-streaming fallback");
                self.provider
                    .complete_with_tools(request)
                    .await
                    .map_err(TurnError::LlmFailed)
            }
            Err(e) => Err(TurnError::LlmFailed(e)),
        }
    }

    /// Processes the LLM response and determines the next action.
    fn process_finish_reason(
        &self,
        response: ToolCompletionResponse,
        messages: &mut Vec<ChatMessage>,
        token_usage: &mut TokenUsage,
    ) -> Result<NextAction, TurnError> {
        let ToolCompletionResponse {
            content,
            reasoning_content,
            tool_calls: response_tool_calls,
            input_tokens,
            output_tokens,
            finish_reason,
            ..
        } = response;

        // Track token usage
        token_usage.input_tokens += input_tokens;
        token_usage.output_tokens += output_tokens;
        token_usage.total_tokens += input_tokens + output_tokens;

        match finish_reason {
            FinishReason::Stop => {
                if content.as_deref().is_some_and(|value| !value.is_empty())
                    || reasoning_content
                        .as_deref()
                        .is_some_and(|value| !value.is_empty())
                {
                    messages.push(ChatMessage::assistant_with_reasoning(
                        content.unwrap_or_default(),
                        reasoning_content,
                    ));
                }

                Ok(NextAction::Return(TurnOutput {
                    messages: std::mem::take(messages),
                    token_usage: token_usage.clone(),
                }))
            }
            FinishReason::ToolUse => {
                // Limit tool calls based on max_tool_calls config
                let tool_calls: Vec<ToolCall> = match self.config.max_tool_calls {
                    Some(max) if response_tool_calls.len() > max as usize => {
                        tracing::debug!(
                            requested = response_tool_calls.len(),
                            max_allowed = max,
                            "Limiting tool calls per iteration"
                        );
                        response_tool_calls.into_iter().take(max as usize).collect()
                    }
                    _ => response_tool_calls,
                };

                // Add assistant message with tool_calls to history
                let assistant_msg = ChatMessage::assistant_with_tool_calls_and_reasoning(
                    content.clone(),
                    tool_calls.clone(),
                    reasoning_content,
                );
                messages.push(assistant_msg);

                Ok(NextAction::ContinueWithTools {
                    tool_calls,
                    content,
                })
            }
            FinishReason::Length => Ok(NextAction::LengthExceeded),
            FinishReason::ContentFilter | FinishReason::Unknown => {
                // For content filter or unknown reasons, return what we have
                if content.as_deref().is_some_and(|value| !value.is_empty())
                    || reasoning_content
                        .as_deref()
                        .is_some_and(|value| !value.is_empty())
                {
                    messages.push(ChatMessage::assistant_with_reasoning(
                        content.unwrap_or_default(),
                        reasoning_content,
                    ));
                }

                Ok(NextAction::Return(TurnOutput {
                    messages: std::mem::take(messages),
                    token_usage: token_usage.clone(),
                }))
            }
        }
    }

    /// Executes multiple tool calls in parallel.
    async fn execute_tools_parallel(
        &self,
        tool_calls: Vec<ToolCall>,
        tool_timeout_secs: u64,
    ) -> Vec<ToolExecutionResult> {
        let futures: Vec<_> = tool_calls
            .into_iter()
            .map(|tool_call| self.execute_single_tool(tool_call, tool_timeout_secs))
            .collect();

        join_all(futures).await
    }

    /// Executes a single tool call with hooks and timeout.
    async fn execute_single_tool(
        &self,
        tool_call: ToolCall,
        tool_timeout_secs: u64,
    ) -> ToolExecutionResult {
        let tool_call_id = tool_call.id.clone();
        let tool_name = tool_call.name.clone();
        let tool_input = tool_call.arguments.clone();

        // Find the tool in self.tools
        let tool = self.tools.iter().find(|t| t.name() == tool_name).cloned();

        // Fire BeforeToolCall hook
        let ctx = ToolHookContext {
            event: HookEvent::BeforeToolCall,
            tool_name: tool_name.clone(),
            tool_call_id: tool_call_id.clone(),
            tool_input: tool_input.clone(),
            tool_result: None,
            error: None,
            tool_manager: tool.clone(),
            thread_event_sender: Some(self.thread_event_tx.clone()),
            thread_id: Some(self.thread_id.clone()),
            turn_number: Some(self.turn_number),
        };

        if let Ok(HookAction::Block(reason)) = self
            .fire_hooks(HookEvent::BeforeToolCall, &HookContext::ToolEvent(ctx))
            .await
        {
            // Hook blocked the tool call
            let content = format!("Tool call blocked: {}", reason);

            // Fire AfterToolCall hook with error
            let after_ctx = ToolHookContext {
                event: HookEvent::AfterToolCall,
                tool_name: tool_name.clone(),
                tool_call_id: tool_call_id.clone(),
                tool_input,
                tool_result: None,
                error: Some(reason),
                tool_manager: None,
                thread_event_sender: Some(self.thread_event_tx.clone()),
                thread_id: Some(self.thread_id.clone()),
                turn_number: Some(self.turn_number),
            };
            let _ = self
                .fire_hooks(HookEvent::AfterToolCall, &HookContext::ToolEvent(after_ctx))
                .await;

            return ToolExecutionResult {
                tool_call_id,
                name: tool_name,
                content,
            };
        }

        // Send ToolStarted events
        let _ = self.thread_event_tx.send(ThreadEvent::ToolStarted {
            thread_id: self.thread_id.clone(),
            turn_number: self.turn_number,
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            arguments: tool_input.clone(),
        });
        let _ = self.stream_tx.send(TurnStreamEvent::ToolStarted {
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            arguments: tool_input.clone(),
        });

        // Execute the tool with timeout
        let timeout_duration = std::time::Duration::from_secs(tool_timeout_secs);
        let execute_future = async {
            if let Some(tool) = tool {
                tool.execute(tool_input.clone()).await
            } else {
                Err(argus_protocol::tool::ToolError::NotFound {
                    id: tool_name.clone(),
                })
            }
        };

        let result = match timeout(timeout_duration, execute_future).await {
            Ok(Ok(value)) => Ok(value),
            Ok(Err(e)) => Err(e.to_string()),
            Err(Elapsed { .. }) => Err(format!(
                "Tool execution timed out after {}s",
                tool_timeout_secs
            )),
        };

        // Send ToolCompleted events
        let event_result = match &result {
            Ok(value) => Ok(value.clone()),
            Err(e) => Err(e.clone()),
        };
        let _ = self.thread_event_tx.send(ThreadEvent::ToolCompleted {
            thread_id: self.thread_id.clone(),
            turn_number: self.turn_number,
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            result: event_result.clone(),
        });
        let _ = self.stream_tx.send(TurnStreamEvent::ToolCompleted {
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            result: event_result,
        });

        // Fire AfterToolCall hook
        let (tool_result, error) = match &result {
            Ok(value) => (Some(value.clone()), None),
            Err(e) => (None, Some(e.clone())),
        };
        let ctx = ToolHookContext {
            event: HookEvent::AfterToolCall,
            tool_name: tool_name.clone(),
            tool_call_id: tool_call_id.clone(),
            tool_input,
            tool_result,
            error,
            tool_manager: None,
            thread_event_sender: Some(self.thread_event_tx.clone()),
            thread_id: Some(self.thread_id.clone()),
            turn_number: Some(self.turn_number),
        };
        let _ = self
            .fire_hooks(HookEvent::AfterToolCall, &HookContext::ToolEvent(ctx))
            .await;

        // Convert result to string content
        let content = match result {
            Ok(value) => serde_json::to_string(&value).unwrap_or_else(|e| {
                format!("{{\"error\": \"Failed to serialize result: {}\"}}", e)
            }),
            Err(e) => format!("{{\"error\": \"{}\"}}", e),
        };

        ToolExecutionResult {
            tool_call_id,
            name: tool_name,
            content,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tokio::sync::broadcast;

    #[test]
    fn test_generate_turn_id() {
        let id = generate_turn_id("thread-123", 5);
        assert_eq!(id, "thread-123-turn-5");
    }

    #[test]
    fn test_turn_builder_requires_turn_number_and_thread_id() {
        // This test verifies the builder API
        // Actual builder validation will be done in integration tests
    }

    #[test]
    fn test_turn_debug_format() {
        // Create channels for testing
        let (stream_tx, _): (broadcast::Sender<TurnStreamEvent>, _) = broadcast::channel(256);
        let (thread_event_tx, _): (broadcast::Sender<ThreadEvent>, _) = broadcast::channel(256);

        // Note: We can't easily test this without a mock provider
        // This is just a placeholder test to verify channel creation works
        let _ = (stream_tx, thread_event_tx);
    }
}
