//! Turn struct for managing turn lifecycle and execution.
//!
//! This module defines the `Turn` struct, which owns its resources (tools and hooks)
//! and is responsible only for execution logic. Construction is handled by `TurnBuilder`
//! (auto-generated by `derive_builder`) or by the Thread layer.

use std::sync::Arc;

use derive_builder::Builder;
use futures_util::{StreamExt, future::join_all};
use tokio::sync::{broadcast, Mutex};
use tokio::time::{error::Elapsed, timeout};
use tracing;

use argus_protocol::llm::{
    ChatMessage, FinishReason, LlmProvider, LlmStreamEvent, ToolCall, ToolCompletionRequest,
    ToolCompletionResponse, ToolDefinition,
};
use argus_protocol::tool::NamedTool;
use argus_protocol::{
    AgentRecord, BeforeCallLLMContext, HookAction, HookContext, HookEvent, HookHandler,
    ThreadEvent, TokenUsage, ToolHookContext, sanitize_tool_output,
};

use super::events::TurnLogEvent;
use super::trace::{TraceConfig, TraceWriter};
use super::tool_context::{set_current_agent_id, clear_current_agent_id};
use super::{TurnConfig, TurnError, TurnOutput, TurnStreamEvent};

/// Turn identifier generator (simple counter for now).
fn generate_turn_id(thread_id: &str, turn_number: u32) -> String {
    format!("{}-turn-{}", thread_id, turn_number)
}

/// Result of processing an LLM response's finish_reason.
enum NextAction {
    /// Turn is complete, return the output.
    Return(TurnOutput),
    /// Continue with tool execution.
    ContinueWithTools {
        tool_calls: Vec<ToolCall>,
        #[allow(dead_code)]
        content: Option<String>,
    },
    /// Context length exceeded.
    LengthExceeded,
}

/// Result of a tool execution.
struct ToolExecutionResult {
    tool_call_id: String,
    name: String,
    content: String,
    #[allow(dead_code)]
    duration_ms: u64,
}

/// Accumulates streaming events into a complete response.
struct StreamingAccumulator {
    content: String,
    reasoning_content: String,
    tool_calls: Vec<(Option<String>, Option<String>, String)>,
    input_tokens: u32,
    output_tokens: u32,
    finish_reason: FinishReason,
}

impl StreamingAccumulator {
    fn new() -> Self {
        Self {
            content: String::new(),
            reasoning_content: String::new(),
            tool_calls: Vec::new(),
            input_tokens: 0,
            output_tokens: 0,
            finish_reason: FinishReason::Stop,
        }
    }

    fn process(&mut self, event: LlmStreamEvent) {
        match event {
            LlmStreamEvent::ReasoningDelta { delta } => {
                self.reasoning_content.push_str(&delta);
            }
            LlmStreamEvent::ContentDelta { delta } => {
                self.content.push_str(&delta);
            }
            LlmStreamEvent::ToolCallDelta(tc) => {
                // Ensure we have enough slots
                while self.tool_calls.len() <= tc.index {
                    self.tool_calls.push((None, None, String::new()));
                }
                if let Some(id) = tc.id {
                    self.tool_calls[tc.index].0 = Some(id);
                }
                if let Some(name) = tc.name {
                    self.tool_calls[tc.index].1 = Some(name);
                }
                if let Some(args_delta) = tc.arguments_delta {
                    self.tool_calls[tc.index].2.push_str(&args_delta);
                }
            }
            LlmStreamEvent::Usage {
                input_tokens,
                output_tokens,
            } => {
                self.input_tokens = input_tokens;
                self.output_tokens = output_tokens;
            }
            LlmStreamEvent::Finished { finish_reason } => {
                self.finish_reason = finish_reason;
            }
            LlmStreamEvent::RetryAttempt { .. } => {
                // Retry events are informational and forwarded to subscribers,
                // but don't affect the accumulated response state
            }
        }
    }

    fn into_response(self) -> ToolCompletionResponse {
        // Convert accumulated tool calls to ToolCall structs
        let tool_calls: Vec<ToolCall> = self
            .tool_calls
            .into_iter()
            .filter_map(|(id, name, args)| {
                Some(ToolCall {
                    id: id?,
                    name: name?,
                    arguments: serde_json::from_str(&args).unwrap_or(serde_json::Value::Null),
                })
            })
            .collect();

        ToolCompletionResponse {
            content: if self.content.is_empty() {
                None
            } else {
                Some(self.content)
            },
            reasoning_content: if self.reasoning_content.is_empty() {
                None
            } else {
                Some(self.reasoning_content)
            },
            tool_calls,
            input_tokens: self.input_tokens,
            output_tokens: self.output_tokens,
            finish_reason: self.finish_reason,
            cache_read_input_tokens: 0,
            cache_creation_input_tokens: 0,
        }
    }
}

/// A Turn represents a single execution cycle in a conversation.
///
/// The Turn owns its resources (tools and hooks) directly and is responsible
/// only for execution logic. Construction is handled by `TurnBuilder` or the Thread layer.
///
/// # Lifecycle
///
/// 1. **Construction**: Built via `TurnBuilder` with all required fields
/// 2. **Execution**: Call `.execute()` to run the turn (consumes self)
/// 3. **Completion**: Returns `TurnOutput` with updated messages and token usage
///
/// # Example
///
/// ```ignore
/// use argus_turn::{Turn, TurnBuilder};
/// use argus_protocol::llm::ChatMessage;
///
/// let turn = TurnBuilder::new()
///     .turn_number(1)
///     .thread_id("thread-123".to_string())
///     .messages(vec![ChatMessage::user("Hello!")])
///     .provider(provider)
///     .tools(vec![Arc::new(my_tool)])
///     .hooks(vec![Arc::new(my_hook)])
///     .config(TurnConfig::default())
///     .stream_tx(stream_tx)
///     .thread_event_tx(thread_event_tx)
///     .build()?;
///
/// let output = turn.execute().await?;
/// ```
#[derive(Builder)]
#[builder(pattern = "owned", build_fn(error = "TurnError"), name = "TurnBuilder")]
pub struct Turn {
    /// Turn identifier (auto-generated from thread_id and turn_number).
    #[builder(
        default = "generate_turn_id(self.thread_id.as_ref().unwrap_or(&\"unknown\".to_string()), *self.turn_number.as_ref().unwrap_or(&0))"
    )]
    pub id: String,

    /// Turn number (sequence in the thread).
    #[builder(setter(custom))]
    turn_number: u32,

    /// Thread identifier.
    #[builder(setter(custom))]
    thread_id: String,

    /// Session identifier (for callback).
    #[builder(default, setter(strip_option))]
    session_id: Option<argus_protocol::SessionId>,

    /// Message history for this turn.
    messages: Vec<ChatMessage>,

    /// LLM provider for completion requests.
    provider: Arc<dyn LlmProvider>,

    /// Tools available for this turn (direct ownership, no ToolManager needed).
    #[builder(default)]
    tools: Vec<Arc<dyn NamedTool>>,

    /// Hooks for lifecycle events (direct ownership, no HookRegistry needed).
    #[builder(default)]
    hooks: Vec<Arc<dyn HookHandler>>,

    /// Turn execution configuration.
    #[builder(default)]
    config: TurnConfig,

    /// Agent record (shared from Thread).
    agent_record: Arc<AgentRecord>,

    /// Internal stream event sender.
    stream_tx: broadcast::Sender<TurnStreamEvent>,

    /// Thread event sender for broadcasting to subscribers.
    thread_event_tx: broadcast::Sender<ThreadEvent>,

    /// Event forwarder task handle (cleaned up on drop).
    #[builder(default)]
    _forwarder_handle: Option<tokio::task::JoinHandle<()>>,

    /// Trace configuration.
    #[builder(default, setter(strip_option))]
    trace_config: Option<TraceConfig>,

    /// Trace writer (created at execute start if enabled).
    #[builder(default, setter(strip_option))]
    #[allow(dead_code)]
    trace_writer: Option<TraceWriter>,
}

impl TurnBuilder {
    /// Set turn number.
    pub fn turn_number(mut self, value: u32) -> Self {
        self.turn_number = Some(value);
        self
    }

    /// Set thread ID.
    pub fn thread_id(mut self, value: String) -> Self {
        self.thread_id = Some(value);
        self
    }
}

impl std::fmt::Debug for Turn {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Turn")
            .field("id", &self.id)
            .field("turn_number", &self.turn_number)
            .field("thread_id", &self.thread_id)
            .field("messages", &self.messages.len())
            .field("provider", &self.provider.model_name())
            .field("tools", &self.tools.len())
            .field("hooks", &self.hooks.len())
            .field("config", &self.config)
            .finish()
    }
}

impl Turn {
    /// Execute the turn and return the output.
    ///
    /// This method:
    /// 1. Spawns the event forwarder task
    /// 2. Executes the main LLM → Tool → LLM loop
    /// 3. Sends TurnCompleted/TurnFailed event
    /// 4. Sends Idle event
    /// 5. Returns TurnOutput with updated messages and token usage
    ///
    /// # Errors
    ///
    /// Returns `TurnError` for:
    /// - LLM failures
    /// - Tool execution failures
    /// - Hook blocks
    /// - Max iterations exceeded
    pub async fn execute(mut self) -> Result<TurnOutput, TurnError> {
        // Spawn event forwarder — clone stream_tx so it lives in the forwarder task.
        // This prevents the channel from closing when the Turn is dropped.
        self._forwarder_handle = Some(Self::spawn_event_forwarder(
            self.stream_tx.clone(),
            self.thread_event_tx.clone(),
            self.thread_id.clone(),
            self.turn_number,
        ));

        // Create trace writer if configured
        #[allow(unused_variables)]
        let mut trace_writer = match self.trace_config.as_ref() {
            Some(config) if config.enabled => {
                let mut base_dir = config.trace_dir.clone();
                if let Some(session_id) = &config.session_id {
                    base_dir = base_dir.join(session_id.to_string());
                }
                base_dir = base_dir.join(&self.thread_id);
                match TraceWriter::new(&base_dir, self.turn_number, config).await {
                    Ok(writer) => Some(writer),
                    Err(e) => {
                        tracing::warn!(
                            thread_id = %self.thread_id,
                            error = %e,
                            "Failed to create trace writer, continuing without tracing"
                        );
                        None
                    }
                }
            }
            _ => None,
        };

        // Write TurnStart event if tracing is enabled
        if let Some(config) = self.trace_config.as_ref() {
            if config.enabled {
                if let Some(writer) = trace_writer.as_mut() {
                    if let (Some(sp), Some(model)) = (&config.system_prompt, &config.model) {
                        let _ = writer.write_event(&TurnLogEvent::TurnStart {
                            system_prompt: sp.clone(),
                            model: model.clone(),
                        }).await;
                    }
                    for msg in self.messages.iter() {
                        if let ChatMessage { role: argus_protocol::llm::Role::User, content, .. } = msg {
                            let _ = writer.write_event(&TurnLogEvent::UserInput {
                                content: content.clone(),
                                role: "user".to_string(),
                            }).await;
                        }
                    }
                }
            }
        }

        tracing::info!(
            thread_id = %self.thread_id,
            turn_number = %self.turn_number,
            tool_count = %self.tools.len(),
            hook_count = %self.hooks.len(),
            "Turn execution started"
        );

        // Execute main loop (takes ownership of trace_writer)
        let loop_result = self.execute_loop(trace_writer).await;
        let (result, trace_writer) = match loop_result {
            Ok((output, tw)) => (Ok(output), tw),
            Err(e) => (Err(e), None),
        };

        tracing::info!(
            thread_id = %self.thread_id,
            turn_number = %self.turn_number,
            result = ?result.as_ref().map(|_| "ok"),
            "Turn execution completed"
        );

        // Invoke on_turn_complete callback if configured
        if let (Some(callback), Some(session_id)) =
            (&self.config.on_turn_complete, &self.session_id)
        {
            callback(*session_id, self.turn_number);
        }

        // Finalize trace - handles both success and failure cases
        if let Some(writer) = trace_writer {
            match &result {
                Ok(output) => {
                    if let Err(e) = writer.finish_success(&output.token_usage).await {
                        tracing::warn!(
                            thread_id = %self.thread_id,
                            error = %e,
                            "Failed to finalize trace on success"
                        );
                    }
                }
                Err(error) => {
                    if let Err(e) = writer.finish_failure(&error.to_string()).await {
                        tracing::warn!(
                            thread_id = %self.thread_id,
                            error = %e,
                            "Failed to finalize trace on failure"
                        );
                    }
                }
            }
        }

        // Send completion event
        match &result {
            Ok(output) => {
                if let Err(e) = self.thread_event_tx.send(ThreadEvent::TurnCompleted {
                    thread_id: self.thread_id.clone(),
                    turn_number: self.turn_number,
                    token_usage: output.token_usage.clone(),
                }) {
                    tracing::warn!(
                        thread_id = %self.thread_id,
                        error = %e,
                        "Failed to send TurnCompleted event"
                    );
                }
            }
            Err(error) => {
                if let Err(e) = self.thread_event_tx.send(ThreadEvent::TurnFailed {
                    thread_id: self.thread_id.clone(),
                    turn_number: self.turn_number,
                    error: error.to_string(),
                }) {
                    tracing::warn!(
                        thread_id = %self.thread_id,
                        error = %e,
                        "Failed to send TurnFailed event"
                    );
                }
            }
        }

        // Send Idle event
        if let Err(e) = self.thread_event_tx.send(ThreadEvent::Idle {
            thread_id: self.thread_id.clone(),
        }) {
            tracing::warn!(
                thread_id = %self.thread_id,
                error = %e,
                "Failed to send Idle event"
            );
        }

        result
    }

    /// Internal method: spawn event forwarder task.
    ///
    /// Forwards TurnStreamEvent to ThreadEvent for external subscribers.
    /// Returns the JoinHandle so the caller can store it.
    fn spawn_event_forwarder(
        stream_tx: broadcast::Sender<TurnStreamEvent>,
        thread_event_tx: broadcast::Sender<ThreadEvent>,
        thread_id: String,
        turn_number: u32,
    ) -> tokio::task::JoinHandle<()> {
        let mut stream_rx = stream_tx.subscribe();

        tokio::spawn(async move {
            tracing::debug!(
                thread_id = %thread_id,
                turn_number = %turn_number,
                "Event forwarder started"
            );
            while let Ok(event) = stream_rx.recv().await {
                match event {
                    TurnStreamEvent::LlmEvent(llm_event) => {
                        if let Err(e) = thread_event_tx.send(ThreadEvent::Processing {
                            thread_id: thread_id.clone(),
                            turn_number,
                            event: llm_event,
                        }) {
                            tracing::warn!(
                                thread_id = %thread_id,
                                turn_number = %turn_number,
                                error = %e,
                                "Failed to forward LlmEvent to thread_event_tx"
                            );
                        }
                    }
                    TurnStreamEvent::ToolStarted {
                        tool_call_id,
                        tool_name,
                        arguments,
                    } => {
                        if let Err(e) = thread_event_tx.send(ThreadEvent::ToolStarted {
                            thread_id: thread_id.clone(),
                            turn_number,
                            tool_call_id,
                            tool_name,
                            arguments,
                        }) {
                            tracing::warn!(
                                thread_id = %thread_id,
                                turn_number = %turn_number,
                                error = %e,
                                "Failed to forward ToolStarted to thread_event_tx"
                            );
                        }
                    }
                    TurnStreamEvent::ToolCompleted {
                        tool_call_id,
                        tool_name,
                        result,
                    } => {
                        if let Err(e) = thread_event_tx.send(ThreadEvent::ToolCompleted {
                            thread_id: thread_id.clone(),
                            turn_number,
                            tool_call_id,
                            tool_name,
                            result,
                        }) {
                            tracing::warn!(
                                thread_id = %thread_id,
                                turn_number = %turn_number,
                                error = %e,
                                "Failed to forward ToolCompleted to thread_event_tx"
                            );
                        }
                    }
                }
            }
            tracing::warn!(
                thread_id = %thread_id,
                turn_number = %turn_number,
                "Event forwarder stopped (stream channel closed)"
            );
        })
    }

    /// Internal method: trigger hooks and return the action.
    ///
    /// Directly iterates over `self.hooks` (no HookRegistry needed).
    #[allow(dead_code)]
    async fn fire_hooks(
        &self,
        event: HookEvent,
        ctx: &HookContext,
    ) -> Result<HookAction, TurnError> {
        for hook in &self.hooks {
            let action = match event {
                HookEvent::BeforeCallLLM => {
                    let HookContext::BeforeCallLLM(ctx_any) = ctx else {
                        return Err(TurnError::LlmCallBlocked {
                            reason: "Invalid hook context".to_string(),
                        });
                    };
                    hook.on_before_call_llm(ctx_any).await
                }
                HookEvent::BeforeToolCall | HookEvent::AfterToolCall | HookEvent::TurnEnd => {
                    let HookContext::ToolEvent(ctx_any) = ctx else {
                        return Err(TurnError::ToolCallBlocked {
                            reason: "Invalid hook context".to_string(),
                        });
                    };
                    hook.on_tool_event(ctx_any).await
                }
            };

            // Handle blocking actions
            if let HookAction::Block(reason) = action {
                return Ok(HookAction::Block(reason));
            }

            // For modification actions (only BeforeCallLLM), return them
            if !matches!(action, HookAction::Continue) {
                return Ok(action);
            }
        }

        Ok(HookAction::Continue)
    }

    /// Internal method: execute the main LLM → Tool → LLM loop.
    ///
    /// This is where the core execution logic lives.
    #[allow(dead_code)]
    async fn execute_loop(
        &mut self,
        trace_writer: Option<TraceWriter>,
    ) -> Result<(TurnOutput, Option<TraceWriter>), TurnError> {
        let mut messages = std::mem::take(&mut self.messages);
        let max_iterations = self.config.max_iterations.unwrap_or(50);
        let tool_timeout_secs = self.config.tool_timeout_secs.unwrap_or(120);
        let mut token_usage = TokenUsage::default();
        let mut trace_writer = trace_writer;

        // Add system message about max_tool_calls ONCE before loop (not inside to avoid accumulation)
        let max_tool_calls = self.config.max_tool_calls;
        if let Some(max) = max_tool_calls
            && !self.tools.is_empty()
        {
            let system_content = format!(
                "IMPORTANT: You can only call at most {} tool(s) per response. \
                If you need to call multiple tools, please proceed step by step - \
                call tools one at a time and wait for the results before calling the next tool.",
                max
            );
            messages.insert(0, ChatMessage::system(system_content));
        }

        for iteration in 0..max_iterations {
            tracing::debug!(
                thread_id = %self.thread_id,
                turn_number = %self.turn_number,
                iteration = %iteration,
                max_iterations = %max_iterations,
                message_count = %messages.len(),
                "Turn iteration started"
            );

            // Prepare tools from self.tools
            let tools: Vec<ToolDefinition> = self.tools.iter().map(|t| t.definition()).collect();

            // Fire BeforeCallLLM hook (can modify messages/tools or block)
            let ctx = BeforeCallLLMContext {
                messages: messages.clone(),
                tools: tools.clone(),
                iteration,
            };
            match self
                .fire_hooks(HookEvent::BeforeCallLLM, &HookContext::BeforeCallLLM(ctx))
                .await?
            {
                HookAction::Continue => {}
                HookAction::ModifyMessages(modified_messages) => {
                    messages = modified_messages;
                }
                HookAction::ModifyTools(_modified_tools) => {
                    // Tools are re-built from definitions, so we can't easily modify them here
                    // For now, just log a warning
                    tracing::warn!("Hook attempted to modify tools, but this is not yet supported");
                }
                HookAction::Modify {
                    messages: modified_messages,
                    tools: _,
                } => {
                    messages = modified_messages;
                }
                HookAction::Block(reason) => {
                    return Err(TurnError::LlmCallBlocked { reason });
                }
            }

            // Build the request with current messages and tools
            let mut request = ToolCompletionRequest::new(messages.clone(), tools.clone());
            if let Some(max_tokens) = self.agent_record.max_tokens {
                request.max_tokens = Some(max_tokens);
            }
            if let Some(temperature) = self.agent_record.temperature {
                request.temperature = Some(temperature);
            }
            if let Some(thinking_config) = &self.agent_record.thinking_config {
                request.thinking = Some(thinking_config.clone());
            }

            // Call the LLM (streaming mode is always enabled in Turn)

            // Write LLM request event to trace
            if let Some(writer) = trace_writer.as_mut() {
                let llm_req_event = TurnLogEvent::LlmRequest {
                    messages: messages.clone(),
                    tools: tools.iter().map(|t| serde_json::to_value(t).ok().unwrap_or(serde_json::Value::Null)).collect(),
                };
                let _ = writer.write_event(&llm_req_event).await;
            }

            tracing::debug!(
                thread_id = %self.thread_id,
                turn_number = %self.turn_number,
                iteration = %iteration,
                tool_count = %tools.len(),
                message_count = %messages.len(),
                "Calling LLM"
            );
            let response = self.call_llm_streaming(request).await?;
            tracing::debug!(
                thread_id = %self.thread_id,
                turn_number = %self.turn_number,
                iteration = %iteration,
                "LLM call completed"
            );

            // Clone for tracing before processing consumes it
            let trace_response = argus_protocol::llm::ToolCompletionResponse {
                content: response.content.clone(),
                reasoning_content: response.reasoning_content.clone(),
                tool_calls: response.tool_calls.clone(),
                input_tokens: response.input_tokens,
                output_tokens: response.output_tokens,
                finish_reason: response.finish_reason,
                cache_read_input_tokens: response.cache_read_input_tokens,
                cache_creation_input_tokens: response.cache_creation_input_tokens,
            };

            // Process response
            match self.process_finish_reason(response, &mut messages, &mut token_usage)? {
                NextAction::Return(output) => {
                    // Fire TurnEnd hook
                    let ctx = ToolHookContext {
                        event: HookEvent::TurnEnd,
                        tool_name: String::new(),
                        tool_call_id: String::new(),
                        tool_input: serde_json::Value::Null,
                        tool_result: None,
                        error: None,
                        tool_manager: None,
                        thread_event_sender: Some(self.thread_event_tx.clone()),
                        thread_id: Some(self.thread_id.clone()),
                        turn_number: Some(self.turn_number),
                    };
                    // TurnEnd is observe-only, ignore errors
                    let _ = self
                        .fire_hooks(HookEvent::TurnEnd, &HookContext::ToolEvent(ctx))
                        .await;

                    // Record LLM response to trace
                    if let Some(writer) = trace_writer.as_mut() {
                        let llm_resp_event = TurnLogEvent::LlmResponse {
                            content: trace_response.content.clone().unwrap_or_default(),
                            reasoning_content: trace_response.reasoning_content.clone(),
                            tool_calls: trace_response
                                .tool_calls
                                .iter()
                                .filter_map(|tc| serde_json::to_value(tc).ok())
                                .collect(),
                            finish_reason: format!("{:?}", trace_response.finish_reason),
                        };
                        let _ = writer.write_event(&llm_resp_event).await;
                    }

                    return Ok((output, trace_writer));
                }
                NextAction::ContinueWithTools {
                    tool_calls,
                    content,
                } => {
                    tracing::debug!(
                        thread_id = %self.thread_id,
                        turn_number = %self.turn_number,
                        iteration = %iteration,
                        tool_count = %tool_calls.len(),
                        content_preview = %content.as_ref().map(|c| c.chars().take(100).collect::<String>()).unwrap_or_default(),
                        "Tool calls detected, executing tools"
                    );

                    // Execute tools in parallel
                    let trace_writer_arc = Arc::new(Mutex::new(trace_writer.take()));
                    let tool_results = self
                        .execute_tools_parallel(tool_calls, tool_timeout_secs, trace_writer_arc.clone())
                        .await;
                    // Restore trace_writer from Arc after all writes complete
                    if let Ok(mutex) = Arc::try_unwrap(trace_writer_arc) {
                        trace_writer = mutex.into_inner();
                    }

                    // Record LLM response to trace (tool results are written in execute_single_tool)
                    if let Some(writer) = trace_writer.as_mut() {
                        let llm_resp_event = TurnLogEvent::LlmResponse {
                            content: trace_response.content.clone().unwrap_or_default(),
                            reasoning_content: trace_response.reasoning_content.clone(),
                            tool_calls: trace_response
                                .tool_calls
                                .iter()
                                .filter_map(|tc| serde_json::to_value(tc).ok())
                                .collect(),
                            finish_reason: format!("{:?}", trace_response.finish_reason),
                        };
                        let _ = writer.write_event(&llm_resp_event).await;
                    }

                    tracing::debug!(
                        thread_id = %self.thread_id,
                        turn_number = %self.turn_number,
                        iteration = %iteration,
                        result_count = %tool_results.len(),
                        "Tools executed, adding results to message history"
                    );

                    // Add tool result messages to history
                    for result in tool_results {
                        let (sanitized_content, warning) =
                            sanitize_tool_output(&result.content, &self.config.safety_config);

                        if let Some(w) = &warning {
                            tracing::warn!(
                                thread_id = %self.thread_id,
                                turn_number = %self.turn_number,
                                tool_call_id = %result.tool_call_id,
                                tool_name = %result.name,
                                pattern = %w.pattern,
                                original_len = w.original_len,
                                truncated_len = w.truncated_len,
                                "Tool output was truncated"
                            );
                        }

                        let result_len = sanitized_content.len();
                        let preview = sanitized_content.chars().take(200).collect::<String>();
                        tracing::info!(
                            thread_id = %self.thread_id,
                            turn_number = %self.turn_number,
                            tool_call_id = %result.tool_call_id,
                            tool_name = %result.name,
                            result_len,
                            result_preview = %preview,
                            "Tool result added to history"
                        );
                        messages.push(ChatMessage::tool_result(
                            result.tool_call_id,
                            result.name,
                            sanitized_content,
                        ));
                    }

                    // Continue the loop with updated messages
                }
                NextAction::LengthExceeded => {
                    return Err(TurnError::ContextLengthExceeded(
                        (token_usage.input_tokens + token_usage.output_tokens) as usize,
                    ));
                }
            }
        }

        // Max iterations reached
        Err(TurnError::MaxIterationsReached(max_iterations))
    }

    /// Calls the LLM in streaming mode, accumulating the response.
    ///
    /// Falls back to non-streaming if the provider doesn't support streaming.
    async fn call_llm_streaming(
        &self,
        request: ToolCompletionRequest,
    ) -> Result<ToolCompletionResponse, TurnError> {
        match self
            .provider
            .stream_complete_with_tools(request.clone())
            .await
        {
            Ok(mut stream) => {
                tracing::debug!(
                    thread_id = %self.thread_id,
                    turn_number = %self.turn_number,
                    "LLM stream started"
                );
                let mut accumulator = StreamingAccumulator::new();
                while let Some(event_result) = stream.next().await {
                    let event = event_result.map_err(TurnError::LlmFailed)?;
                    // Forward to stream_tx
                    let _ = self
                        .stream_tx
                        .send(TurnStreamEvent::LlmEvent(event.clone()));
                    accumulator.process(event);
                }
                let response = accumulator.into_response();
                tracing::debug!(
                    thread_id = %self.thread_id,
                    turn_number = %self.turn_number,
                    finish_reason = ?response.finish_reason,
                    tool_call_count = %response.tool_calls.len(),
                    "LLM stream completed"
                );
                Ok(response)
            }
            Err(argus_protocol::llm::LlmError::UnsupportedCapability { .. }) => {
                // Fallback to non-streaming
                tracing::debug!("Provider doesn't support streaming, using non-streaming fallback");
                self.provider
                    .complete_with_tools(request)
                    .await
                    .map_err(TurnError::LlmFailed)
            }
            Err(e) => Err(TurnError::LlmFailed(e)),
        }
    }

    /// Processes the LLM response and determines the next action.
    fn process_finish_reason(
        &self,
        response: ToolCompletionResponse,
        messages: &mut Vec<ChatMessage>,
        token_usage: &mut TokenUsage,
    ) -> Result<NextAction, TurnError> {
        let ToolCompletionResponse {
            content,
            reasoning_content,
            tool_calls: response_tool_calls,
            input_tokens,
            output_tokens,
            finish_reason,
            ..
        } = response;

        // Track token usage
        token_usage.input_tokens += input_tokens;
        token_usage.output_tokens += output_tokens;
        token_usage.total_tokens += input_tokens + output_tokens;

        match finish_reason {
            FinishReason::Stop => {
                if content.as_deref().is_some_and(|value| !value.is_empty())
                    || reasoning_content
                        .as_deref()
                        .is_some_and(|value| !value.is_empty())
                {
                    messages.push(ChatMessage::assistant_with_reasoning(
                        content.unwrap_or_default(),
                        reasoning_content,
                    ));
                }

                Ok(NextAction::Return(TurnOutput {
                    messages: std::mem::take(messages),
                    token_usage: token_usage.clone(),
                }))
            }
            FinishReason::ToolUse => {
                // Limit tool calls based on max_tool_calls config
                let tool_calls: Vec<ToolCall> = match self.config.max_tool_calls {
                    Some(max) if response_tool_calls.len() > max as usize => {
                        tracing::debug!(
                            requested = response_tool_calls.len(),
                            max_allowed = max,
                            "Limiting tool calls per iteration"
                        );
                        response_tool_calls.into_iter().take(max as usize).collect()
                    }
                    _ => response_tool_calls,
                };

                // Add assistant message with tool_calls to history
                let assistant_msg = ChatMessage::assistant_with_tool_calls_and_reasoning(
                    content.clone(),
                    tool_calls.clone(),
                    reasoning_content,
                );
                messages.push(assistant_msg);

                Ok(NextAction::ContinueWithTools {
                    tool_calls,
                    content,
                })
            }
            FinishReason::Length => Ok(NextAction::LengthExceeded),
            FinishReason::ContentFilter | FinishReason::Unknown => {
                // If there are actual tool calls, treat as ToolUse (some providers
                // return non-standard finish_reason values when tool calls are present)
                if !response_tool_calls.is_empty() {
                    let tool_calls: Vec<ToolCall> = match self.config.max_tool_calls {
                        Some(max) if response_tool_calls.len() > max as usize => {
                            tracing::debug!(
                                requested = response_tool_calls.len(),
                                max_allowed = max,
                                "Limiting tool calls per iteration"
                            );
                            response_tool_calls.into_iter().take(max as usize).collect()
                        }
                        _ => response_tool_calls,
                    };

                    let assistant_msg = ChatMessage::assistant_with_tool_calls_and_reasoning(
                        content.clone(),
                        tool_calls.clone(),
                        reasoning_content,
                    );
                    messages.push(assistant_msg);

                    Ok(NextAction::ContinueWithTools {
                        tool_calls,
                        content,
                    })
                } else if content.as_deref().is_some_and(|value| !value.is_empty())
                    || reasoning_content
                        .as_deref()
                        .is_some_and(|value| !value.is_empty())
                {
                    messages.push(ChatMessage::assistant_with_reasoning(
                        content.unwrap_or_default(),
                        reasoning_content,
                    ));

                    Ok(NextAction::Return(TurnOutput {
                        messages: std::mem::take(messages),
                        token_usage: token_usage.clone(),
                    }))
                } else {
                    Ok(NextAction::Return(TurnOutput {
                        messages: std::mem::take(messages),
                        token_usage: token_usage.clone(),
                    }))
                }
            }
        }
    }

    /// Executes multiple tool calls in parallel.
    async fn execute_tools_parallel(
        &self,
        tool_calls: Vec<ToolCall>,
        tool_timeout_secs: u64,
        trace_writer: Arc<Mutex<Option<TraceWriter>>>,
    ) -> Vec<ToolExecutionResult> {
        let futures: Vec<_> = tool_calls
            .into_iter()
            .map(|tool_call| self.execute_single_tool(tool_call, tool_timeout_secs, trace_writer.clone()))
            .collect();

        join_all(futures).await
    }

    /// Executes a single tool call with hooks and timeout.
    async fn execute_single_tool(
        &self,
        tool_call: ToolCall,
        tool_timeout_secs: u64,
        trace_writer: Arc<Mutex<Option<TraceWriter>>>,
    ) -> ToolExecutionResult {
        let tool_call_id = tool_call.id.clone();
        let tool_name = tool_call.name.clone();
        let tool_input = tool_call.arguments.clone();

        // Write ToolCallStart event
        {
            let mut guard = trace_writer.lock().await;
            if let Some(writer) = guard.as_mut() {
                let _ = writer.write_event(&TurnLogEvent::ToolCallStart {
                    id: tool_call_id.clone(),
                    name: tool_name.clone(),
                    arguments: tool_input.clone(),
                }).await;
            }
        }

        // Find the tool in self.tools
        let tool = self.tools.iter().find(|t| t.name() == tool_name).cloned();

        // Fire BeforeToolCall hook
        let ctx = ToolHookContext {
            event: HookEvent::BeforeToolCall,
            tool_name: tool_name.clone(),
            tool_call_id: tool_call_id.clone(),
            tool_input: tool_input.clone(),
            tool_result: None,
            error: None,
            tool_manager: tool.clone(),
            thread_event_sender: Some(self.thread_event_tx.clone()),
            thread_id: Some(self.thread_id.clone()),
            turn_number: Some(self.turn_number),
        };

        if let Ok(HookAction::Block(ref reason)) = self
            .fire_hooks(HookEvent::BeforeToolCall, &HookContext::ToolEvent(ctx))
            .await
        {
            // Hook blocked the tool call
            let block_start = std::time::Instant::now();
            let content = format!("Tool call blocked: {}", reason);
            let duration_ms = block_start.elapsed().as_millis() as u64;

            // Write blocked tool result to trace
            {
                let mut guard = trace_writer.lock().await;
                if let Some(writer) = guard.as_mut() {
                    let _ = writer.write_event(&TurnLogEvent::ToolResult {
                        id: tool_call_id.clone(),
                        name: tool_name.clone(),
                        result: content.clone(),
                        duration_ms,
                        error: Some(reason.clone()),
                    }).await;
                }
            }

            // Fire AfterToolCall hook with error
            let after_ctx = ToolHookContext {
                event: HookEvent::AfterToolCall,
                tool_name: tool_name.clone(),
                tool_call_id: tool_call_id.clone(),
                tool_input,
                tool_result: None,
                error: Some(reason.clone()),
                tool_manager: None,
                thread_event_sender: Some(self.thread_event_tx.clone()),
                thread_id: Some(self.thread_id.clone()),
                turn_number: Some(self.turn_number),
            };
            let _ = self
                .fire_hooks(HookEvent::AfterToolCall, &HookContext::ToolEvent(after_ctx))
                .await;

            return ToolExecutionResult {
                tool_call_id,
                name: tool_name,
                content,
                duration_ms,
            };
        }

        // Send ToolStarted events
        if let Err(e) = self.thread_event_tx.send(ThreadEvent::ToolStarted {
            thread_id: self.thread_id.clone(),
            turn_number: self.turn_number,
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            arguments: tool_input.clone(),
        }) {
            tracing::warn!(
                thread_id = %self.thread_id,
                turn_number = %self.turn_number,
                tool_name = %tool_name,
                error = %e,
                "Failed to send ToolStarted event"
            );
        }
        let _ = self.stream_tx.send(TurnStreamEvent::ToolStarted {
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            arguments: tool_input.clone(),
        });

        // Execute the tool with timeout
        let timeout_duration = std::time::Duration::from_secs(tool_timeout_secs);
        set_current_agent_id(self.agent_record.id);
        let start_time = std::time::Instant::now();
        let execute_result = {
            let execute_future = async {
                if let Some(tool) = tool {
                    tracing::debug!(
                        thread_id = %self.thread_id,
                        turn_number = %self.turn_number,
                        tool_call_id = %tool_call_id,
                        tool_name = %tool_name,
                        "Executing tool"
                    );
                    tool.execute(tool_input.clone()).await
                } else {
                    tracing::error!(
                        thread_id = %self.thread_id,
                        turn_number = %self.turn_number,
                        tool_call_id = %tool_call_id,
                        tool_name = %tool_name,
                        available_tools = ?self.tools.iter().map(|t| t.name()).collect::<Vec<_>>(),
                        "Tool not found in registry"
                    );
                    Err(argus_protocol::tool::ToolError::NotFound {
                        id: tool_name.clone(),
                    })
                }
            };
            timeout(timeout_duration, execute_future).await
        };
        clear_current_agent_id();

        let result = match execute_result {
            Ok(Ok(value)) => {
                tracing::info!(
                    thread_id = %self.thread_id,
                    turn_number = %self.turn_number,
                    tool_call_id = %tool_call_id,
                    tool_name = %tool_name,
                    result_preview = %value.to_string().chars().take(200).collect::<String>(),
                    "Tool executed successfully"
                );
                Ok(value)
            }
            Ok(Err(e)) => {
                tracing::warn!(
                    thread_id = %self.thread_id,
                    turn_number = %self.turn_number,
                    tool_call_id = %tool_call_id,
                    tool_name = %tool_name,
                    error = %e,
                    "Tool execution returned error"
                );
                Err(e.to_string())
            }
            Err(Elapsed { .. }) => {
                tracing::error!(
                    thread_id = %self.thread_id,
                    turn_number = %self.turn_number,
                    tool_call_id = %tool_call_id,
                    tool_name = %tool_name,
                    timeout_secs = %tool_timeout_secs,
                    "Tool execution timed out"
                );
                Err(format!(
                    "Tool execution timed out after {}s",
                    tool_timeout_secs
                ))
            }
        };

        // Send ToolCompleted events
        let event_result = match &result {
            Ok(value) => Ok(value.clone()),
            Err(e) => Err(e.clone()),
        };
        if let Err(e) = self.thread_event_tx.send(ThreadEvent::ToolCompleted {
            thread_id: self.thread_id.clone(),
            turn_number: self.turn_number,
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            result: event_result.clone(),
        }) {
            tracing::warn!(
                thread_id = %self.thread_id,
                turn_number = %self.turn_number,
                tool_name = %tool_name,
                error = %e,
                "Failed to send ToolCompleted event"
            );
        }
        let _ = self.stream_tx.send(TurnStreamEvent::ToolCompleted {
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            result: event_result,
        });

        // Fire AfterToolCall hook
        let (tool_result, error) = match &result {
            Ok(value) => (Some(value.clone()), None),
            Err(e) => (None, Some(e.clone())),
        };
        let ctx = ToolHookContext {
            event: HookEvent::AfterToolCall,
            tool_name: tool_name.clone(),
            tool_call_id: tool_call_id.clone(),
            tool_input,
            tool_result,
            error,
            tool_manager: None,
            thread_event_sender: Some(self.thread_event_tx.clone()),
            thread_id: Some(self.thread_id.clone()),
            turn_number: Some(self.turn_number),
        };
        let _ = self
            .fire_hooks(HookEvent::AfterToolCall, &HookContext::ToolEvent(ctx))
            .await;

        // Convert result to string content and measure duration
        let duration_ms = start_time.elapsed().as_millis() as u64;
        let content = match &result {
            Ok(value) => serde_json::to_string(value).unwrap_or_else(|e| {
                format!("{{\"error\": \"Failed to serialize result: {}\"}}", e)
            }),
            Err(e) => format!("{{\"error\": \"{}\"}}", e),
        };

        // Write ToolResult to trace
        {
            let mut guard = trace_writer.lock().await;
            if let Some(writer) = guard.as_mut() {
                let error_str = match &result {
                    Ok(_) => None,
                    Err(e) => Some(e.clone()),
                };
                let _ = writer.write_event(&TurnLogEvent::ToolResult {
                    id: tool_call_id.clone(),
                    name: tool_name.clone(),
                    result: content.clone(),
                    duration_ms,
                    error: error_str,
                }).await;
            }
        }

        ToolExecutionResult {
            tool_call_id,
            name: tool_name,
            content,
            duration_ms,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tokio::sync::{broadcast, Mutex};

    #[test]
    fn test_generate_turn_id() {
        let id = generate_turn_id("thread-123", 5);
        assert_eq!(id, "thread-123-turn-5");
    }

    #[test]
    fn test_turn_builder_requires_turn_number_and_thread_id() {
        // This test verifies the builder API
        // Actual builder validation will be done in integration tests
    }

    #[test]
    fn test_turn_debug_format() {
        // Create channels for testing
        let (stream_tx, _): (broadcast::Sender<TurnStreamEvent>, _) = broadcast::channel(256);
        let (thread_event_tx, _): (broadcast::Sender<ThreadEvent>, _) = broadcast::channel(256);

        // Note: We can't easily test this without a mock provider
        // This is just a placeholder test to verify channel creation works
        let _ = (stream_tx, thread_event_tx);
    }
}
