use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    // ../../ from crates/argus-wing/ to reach root agents directory
    let agents_dir = Path::new(&manifest_dir).join("../../agents");
    let migrations_dir = Path::new(&manifest_dir).join("migrations");

    // Create migrations directory if it doesn't exist
    fs::create_dir_all(&migrations_dir).unwrap();

    // Scan all .toml files in agents directory
    let toml_files: Vec<_> = glob::glob(&agents_dir.join("*.toml").display().to_string())
        .unwrap()
        .filter_map(Result::ok)
        .collect();

    if toml_files.is_empty() {
        // Still create migrations dir but no migration file
        return;
    }

    let mut insert_statements = Vec::new();

    for toml_path in &toml_files {
        let content = fs::read_to_string(toml_path).unwrap();
        let def: TomlAgentDef = toml::from_str(&content).unwrap();

        let tool_names_json = serde_json::to_string(&def.tool_names).unwrap();
        // Use DELETE + INSERT to ensure idempotency (upsert behavior)
        let stmt = format!(
            "DELETE FROM agents WHERE display_name = '{}';\n\
             INSERT INTO agents (display_name, description, version, provider_id, system_prompt, tool_names) \
             VALUES ('{}', '{}', '{}', NULL, '{}', '{}');",
            escape_sql(&def.display_name),
            escape_sql(&def.display_name),
            escape_sql(&def.description),
            escape_sql(&def.version),
            escape_sql(&def.system_prompt),
            tool_names_json,
        );
        insert_statements.push(stmt);
    }

    // Generate migration file with timestamp after existing migrations (20260317*)
    // Use timestamp 20260319000000 to be after 20260317142756
    let migration_name = "20260319000000_seed_builtin_agents.sql";
    let migration_path = migrations_dir.join(migration_name);

    let migration_content = format!(
        "-- Seed builtin agents from TOML files\n\
         -- Generated by build.rs\n\
         \n\
         {}\n",
        insert_statements.join("\n\n")
    );

    fs::write(&migration_path, migration_content).unwrap();

    // Declare dependencies so build reruns when TOML files change
    println!("cargo:rerun-if-changed={}", agents_dir.display());
}

fn escape_sql(s: &str) -> String {
    s.replace('\'', "''")
}

#[derive(serde::Deserialize)]
struct TomlAgentDef {
    #[allow(dead_code)]
    id: Option<String>,
    display_name: String,
    description: String,
    version: String,
    system_prompt: String,
    tool_names: Vec<String>,
}
