use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=agents");

    // Find agents directory relative to build.rs
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let workspace_root = Path::new(&manifest_dir)
        .parent()
        .and_then(|p| p.parent())
        .expect("Could not find workspace root");

    let agents_dir = workspace_root.join("agents");

    if !agents_dir.exists() {
        panic!("agents directory not found at {}", agents_dir.display());
    }

    // Find all .toml files
    let toml_files: Vec<_> = fs::read_dir(&agents_dir)
        .expect("Failed to read agents directory")
        .filter_map(|entry| entry.ok())
        .filter(|entry| {
            entry
                .path()
                .extension()
                .map(|ext| ext == "toml")
                .unwrap_or(false)
        })
        .collect();

    if toml_files.is_empty() {
        panic!("No .toml files found in {}", agents_dir.display());
    }

    // Sort for consistent ordering
    let mut toml_files = toml_files;
    toml_files.sort_by_key(|entry| entry.path().file_name().unwrap().to_string_lossy().to_string());

    // Generate the code
    let mut code = String::from(
        r#"// WARNING: This file is auto-generated by build.rs
// Do not edit manually

/// Get all builtin agent TOML definitions as a slice of strings
pub fn get_builtin_agent_definitions() -> &'static [&'static str] {
    // Relative paths from crates/argus-template/src/ to repository root
    const AGENT_DEFINITIONS: &[&str] = &[
"#,
    );

    for entry in &toml_files {
        let path = entry.path();
        let filename = path.file_name().unwrap().to_string_lossy();
        // Calculate relative path from crates/argus-template/src/manager.rs to agents/
        // crates/argus-template/src/manager.rs -> agents/ is ../../../agents/
        code.push_str(&format!("        include_str!(\"../../../agents/{}\"),\n", filename));
    }

    code.push_str(
        r#"    ];

    AGENT_DEFINITIONS
}
"#,
    );

    // Write to src/generated_agents.rs
    let out_dir = Path::new(&manifest_dir).join("src");
    fs::write(out_dir.join("generated_agents.rs"), code)
        .expect("Failed to write generated_agents.rs");

    println!("cargo:rerun-if-changed=build.rs");
}
