//! Argus Agent - unified turn execution and thread management.
//!
//! This crate provides:
//! - **`Turn`**: single-turn LLM + tool execution engine
//! - **`Thread`**: multi-turn conversation manager (orchestrates Turns)
//!
//! # Architecture
//!
//! The crate has been refactored to use a structural design pattern:
//!
//! - **`Turn`** (new): Owns its resources (tools, hooks) and is responsible only for execution
//! - **`TurnBuilder`**: Auto-generated by `derive_builder` for constructing Turn instances
//! - **`execute_turn()`** (legacy): Backward-compatible wrapper that internally uses `Turn`
//!
//! # Example (New API)
//!
//! ```ignore
//! use argus_agent::{Turn, TurnBuilder};
//! use argus_protocol::llm::ChatMessage;
//! use argus_protocol::tool::NamedTool;
//! use std::sync::Arc;
//!
//! let turn = TurnBuilder::default()
//!     .turn_number(1)
//!     .thread_id("thread-123".to_string())
//!     .messages(vec![ChatMessage::user("Hello!")])
//!     .provider(provider)
//!     .tools(vec![Arc::new(my_tool)])
//!     .hooks(vec![Arc::new(my_hook)])
//!     .config(TurnConfig::default())
//!     .stream_tx(stream_tx)
//!     .thread_event_tx(thread_event_tx)
//!     .build()?;
//!
//! let output = turn.execute().await?;
//! ```
//!
//! # Example (Thread)
//!
//! ```ignore
//! use argus_agent::{Thread, ThreadBuilder, ThreadConfig};
//! use argus_protocol::llm::ChatMessage;
//!
//! let thread = ThreadBuilder::new()
//!     .provider(my_provider)
//!     .compactor(my_compactor)
//!     .build()
//!     .unwrap();
//!
//! thread.send_message("Hello!".to_string()).await.unwrap();
//! ```

mod command;
pub mod compact;
pub mod config;
pub mod error;
pub mod execution;
pub mod history;
pub mod plan_hook;
pub mod plan_store;
pub mod plan_tool;
pub mod thread;
pub mod turn_log_store;

pub mod tool_context;
pub mod trace;
pub mod turn;
pub mod types;

// ---------------------------------------------------------------------------
// Public exports
// ---------------------------------------------------------------------------

// Turn (low-level)
pub use config::{
    OnTurnComplete, TurnConfig, TurnConfigBuilder, TurnInput, TurnInputBuilder, TurnOutput,
    TurnOutputBuilder, TurnStreamEvent,
};
pub use error::{TurnError, TurnLogError};
pub use execution::{ExecutionMode, execute_turn, execute_turn_streaming};
pub use trace::TraceConfig;
pub use turn::{Turn, TurnBuilder, TurnCancellation};

// Thread (high-level)
pub use compact::{CompactResult, Compactor, LlmCompactor};
pub use config::ThreadConfig;
pub use error::{CompactError, ThreadError};
pub use plan_store::FilePlanStore;
pub use thread::{Thread, ThreadBuilder};
pub use types::{ThreadInfo, ThreadState};

// Re-export hook types from argus-protocol for convenience
pub use argus_protocol::{HookAction, HookEvent, HookHandler, HookRegistry, ToolHookContext};
