//! Turn struct for managing turn lifecycle and execution.
//!
//! This module defines the `Turn` struct, which owns its resources (tools and hooks)
//! and is responsible only for execution logic. Construction is handled by `TurnBuilder`
//! (auto-generated by `derive_builder`) or by the Thread layer.

use std::sync::Arc;

use derive_builder::Builder;
use futures_util::{StreamExt, future::join_all};
use tokio::sync::{Mutex, broadcast, mpsc, oneshot, watch};
use tokio::time::{error::Elapsed, timeout};
use tracing;

use super::history::InFlightTurnShared;
use super::tool_context::{clear_current_agent_id, set_current_agent_id};
use super::{TurnConfig, TurnError, TurnOutput, TurnStreamEvent};
use argus_protocol::llm::{
    ChatMessage, CompletionRequest, CompletionResponse, FinishReason, LlmProvider, LlmStreamEvent,
    ToolCall, ToolDefinition,
};
use argus_protocol::tool::NamedTool;
use argus_protocol::{
    AgentRecord, HookAction, HookEvent, HookHandler, ThreadEvent, ThreadMailbox, TokenUsage,
    ToolExecutionContext, ToolHookContext, ids::ThreadId, sanitize_tool_output,
};

/// Progress emitted while a turn is executing.
#[derive(Debug, Clone)]
pub enum TurnProgress {
    /// A streamed LLM event.
    LlmEvent(LlmStreamEvent),
    /// A tool call has started.
    ToolStarted {
        tool_call_id: String,
        tool_name: String,
        arguments: serde_json::Value,
    },
    /// A tool call has completed.
    ToolCompleted {
        tool_call_id: String,
        tool_name: String,
        result: Result<serde_json::Value, String>,
    },
    /// The turn paused for approval.
    WaitingForApproval {
        thread_id: String,
        turn_number: u32,
        request: argus_protocol::ApprovalRequest,
    },
    /// The approval decision has resolved and the turn may continue.
    ApprovalResolved {
        thread_id: String,
        turn_number: u32,
        response: argus_protocol::ApprovalResponse,
    },
    /// The turn completed successfully.
    Completed(TurnOutput),
    /// The turn failed or was cancelled.
    Failed { error: String },
}

/// Handle for observing turn progress as it happens and awaiting the final result.
#[derive(Debug)]
pub struct TurnExecution {
    progress_rx: mpsc::UnboundedReceiver<TurnProgress>,
    result_rx: oneshot::Receiver<Result<TurnOutput, TurnError>>,
}

/// Fully collected progress plus the final turn result.
#[derive(Debug)]
pub struct CollectedTurnExecution {
    pub progress: Vec<TurnProgress>,
    pub result: Result<TurnOutput, TurnError>,
}

impl TurnExecution {
    /// Receive the next progress item as the turn runs.
    pub async fn recv(&mut self) -> Option<TurnProgress> {
        self.progress_rx.recv().await
    }

    /// Wait for the terminal turn result.
    pub async fn finish(self) -> Result<TurnOutput, TurnError> {
        let TurnExecution {
            progress_rx,
            result_rx,
        } = self;
        drop(progress_rx);

        match result_rx.await {
            Ok(result) => result,
            Err(error) => Err(TurnError::BuildFailed(format!(
                "turn execution task failed: {error}"
            ))),
        }
    }

    /// Collect every progress item until the turn completes.
    pub async fn collect(mut self) -> CollectedTurnExecution {
        let mut progress = Vec::new();
        while let Some(item) = self.recv().await {
            progress.push(item);
        }

        let result = match self.result_rx.await {
            Ok(result) => result,
            Err(error) => Err(TurnError::BuildFailed(format!(
                "turn execution task failed: {error}"
            ))),
        };

        CollectedTurnExecution { progress, result }
    }
}

/// Cancellation primitive used to stop an active turn.
///
/// This token is cloneable so the runtime can hold a handle to cancel the active
/// turn while the turn itself periodically checks for cancellation.
#[derive(Clone, Debug)]
pub struct TurnCancellation {
    tx: watch::Sender<bool>,
    rx: watch::Receiver<bool>,
}

impl TurnCancellation {
    #[must_use]
    pub fn new() -> Self {
        let (tx, rx) = watch::channel(false);
        Self { tx, rx }
    }

    pub fn cancel(&self) {
        let _ = self.tx.send(true);
    }

    #[must_use]
    pub fn is_cancelled(&self) -> bool {
        *self.rx.borrow()
    }

    #[must_use]
    pub fn subscribe(&self) -> watch::Receiver<bool> {
        self.rx.clone()
    }

    pub async fn cancelled(&self) {
        if self.is_cancelled() {
            return;
        }

        let mut rx = self.subscribe();
        loop {
            if rx.changed().await.is_err() {
                return;
            }
            if *rx.borrow() {
                return;
            }
        }
    }
}

impl Default for TurnCancellation {
    fn default() -> Self {
        Self::new()
    }
}

/// Turn identifier generator (simple counter for now).
fn generate_turn_id(thread_id: &str, turn_number: u32) -> String {
    format!("{}-turn-{}", thread_id, turn_number)
}

fn dummy_control_tx() -> mpsc::UnboundedSender<argus_protocol::ThreadControlEvent> {
    let (tx, _rx) = mpsc::unbounded_channel();
    tx
}

fn default_mailbox() -> Arc<Mutex<ThreadMailbox>> {
    Arc::new(Mutex::new(ThreadMailbox::default()))
}

/// Result of processing an LLM response's finish_reason.
enum NextAction {
    /// Turn is complete, return the output.
    Return(TurnOutput),
    /// Continue with tool execution.
    ContinueWithTools {
        tool_calls: Vec<ToolCall>,
        content: Option<String>,
    },
    /// Context length exceeded.
    LengthExceeded,
}

enum StreamingCallOutcome {
    Completed(CompletionResponse),
    Failed {
        partial_response: CompletionResponse,
        error: argus_protocol::llm::LlmError,
    },
}

/// Result of a tool execution.
struct ToolExecutionResult {
    tool_call_id: String,
    name: String,
    content: String,
}

/// Accumulates streaming events into a complete response.
struct StreamingAccumulator {
    content: String,
    reasoning_content: String,
    tool_calls: Vec<(Option<String>, Option<String>, String)>,
    usage: argus_protocol::LlmUsage,
    finish_reason: FinishReason,
}

impl StreamingAccumulator {
    fn new() -> Self {
        Self {
            content: String::new(),
            reasoning_content: String::new(),
            tool_calls: Vec::new(),
            usage: argus_protocol::LlmUsage::default(),
            finish_reason: FinishReason::Stop,
        }
    }

    fn process(&mut self, event: LlmStreamEvent) {
        match event {
            LlmStreamEvent::ReasoningDelta { delta } => {
                self.reasoning_content.push_str(&delta);
            }
            LlmStreamEvent::ContentDelta { delta } => {
                self.content.push_str(&delta);
            }
            LlmStreamEvent::ToolCallDelta(tc) => {
                // Ensure we have enough slots
                while self.tool_calls.len() <= tc.index {
                    self.tool_calls.push((None, None, String::new()));
                }
                if let Some(id) = tc.id {
                    self.tool_calls[tc.index].0 = Some(id);
                }
                if let Some(name) = tc.name {
                    self.tool_calls[tc.index].1 = Some(name);
                }
                if let Some(args_delta) = tc.arguments_delta {
                    self.tool_calls[tc.index].2.push_str(&args_delta);
                }
            }
            LlmStreamEvent::Usage { usage } => {
                self.usage = usage;
            }
            LlmStreamEvent::Finished { finish_reason } => {
                self.finish_reason = finish_reason;
            }
            LlmStreamEvent::RetryAttempt { .. } => {
                // Retry events are informational and forwarded to subscribers,
                // but don't affect the accumulated response state
            }
        }
    }

    fn into_response(self) -> CompletionResponse {
        // Convert accumulated tool calls to ToolCall structs
        let tool_calls: Vec<ToolCall> = self
            .tool_calls
            .into_iter()
            .filter_map(|(id, name, args)| {
                Some(ToolCall {
                    id: id?,
                    name: name?,
                    arguments: serde_json::from_str(&args).unwrap_or(serde_json::Value::Null),
                })
            })
            .collect();

        CompletionResponse {
            content: if self.content.is_empty() {
                None
            } else {
                Some(self.content)
            },
            reasoning_content: if self.reasoning_content.is_empty() {
                None
            } else {
                Some(self.reasoning_content)
            },
            tool_calls,
            input_tokens: self.usage.input_tokens,
            output_tokens: self.usage.output_tokens,
            finish_reason: self.finish_reason,
            cache_read_input_tokens: self.usage.cache_read_input_tokens,
            cache_creation_input_tokens: self.usage.cache_creation_input_tokens,
        }
    }
}

#[derive(Clone, Default)]
pub(crate) struct TurnSharedContext {
    state: Arc<InFlightTurnShared>,
}

impl TurnSharedContext {
    pub(crate) fn for_thread(state: Arc<InFlightTurnShared>) -> Self {
        Self { state }
    }

    fn resolved_tools(&self) -> Vec<Arc<dyn NamedTool>> {
        self.state.tools.iter().cloned().collect()
    }

    fn resolved_hooks(&self) -> Vec<Arc<dyn HookHandler>> {
        self.state.hooks.iter().cloned().collect()
    }

    fn find_tool(&self, tool_name: &str) -> Option<Arc<dyn NamedTool>> {
        self.resolved_tools()
            .into_iter()
            .find(|tool| tool.name() == tool_name)
    }
}

/// A Turn represents a single execution cycle in a conversation.
///
/// The Turn owns its resources (tools and hooks) directly and is responsible
/// only for execution logic. Construction is handled by `TurnBuilder` or the Thread layer.
///
/// # Lifecycle
///
/// 1. **Construction**: Built via `TurnBuilder` with all required fields
/// 2. **Execution**: Call `.execute()` to run the turn (consumes self)
/// 3. **Completion**: Returns `TurnOutput` with appended messages and token usage
///
/// # Example
///
/// ```ignore
/// use argus_agent::{Turn, TurnBuilder};
/// use argus_protocol::llm::ChatMessage;
///
/// let turn = TurnBuilder::new()
///     .turn_number(1)
///     .thread_id("thread-123".to_string())
///     .messages(vec![ChatMessage::user("Hello!")])
///     .provider(provider)
///     .tools(vec![Arc::new(my_tool)])
///     .hooks(vec![Arc::new(my_hook)])
///     .config(TurnConfig::default())
///     .stream_tx(stream_tx)
///     .thread_event_tx(thread_event_tx)
///     .build()?;
///
/// let output = turn.execute().await?;
/// ```
#[derive(Builder)]
#[builder(pattern = "owned", build_fn(error = "TurnError"), name = "TurnBuilder")]
pub struct Turn {
    /// Turn identifier (auto-generated from thread_id and turn_number).
    #[builder(
        default = "generate_turn_id(self.thread_id.as_ref().unwrap_or(&\"unknown\".to_string()), *self.turn_number.as_ref().unwrap_or(&0))"
    )]
    pub id: String,

    /// Turn number (sequence in the thread).
    #[builder(setter(custom))]
    turn_number: u32,

    /// Thread identifier.
    #[builder(setter(custom))]
    thread_id: String,

    /// Stable routing thread used for control-plane callbacks and nested jobs.
    #[builder(default = "ThreadId::new()", setter(custom))]
    originating_thread_id: ThreadId,

    /// Session identifier (for callback).
    #[builder(default, setter(strip_option))]
    session_id: Option<argus_protocol::SessionId>,

    /// Shared thread-owned context consulted during execution.
    #[builder(setter(custom), default = "Arc::new(TurnSharedContext::default())")]
    shared: Arc<TurnSharedContext>,

    /// Messages appended during this turn.
    #[builder(default)]
    pending_messages: Vec<ChatMessage>,

    /// LLM provider for completion requests.
    provider: Arc<dyn LlmProvider>,

    /// Turn execution configuration.
    #[builder(default)]
    config: TurnConfig,

    /// Agent record (shared from Thread).
    agent_record: Arc<AgentRecord>,

    /// Internal stream event sender.
    stream_tx: broadcast::Sender<TurnStreamEvent>,

    /// Thread event sender for broadcasting to subscribers.
    thread_event_tx: broadcast::Sender<ThreadEvent>,

    /// Control sender used by nested tool executions.
    #[builder(default = "dummy_control_tx()")]
    control_tx: mpsc::UnboundedSender<argus_protocol::ThreadControlEvent>,

    /// Shared thread mailbox consulted before each loop iteration.
    ///
    /// Note: this mailbox is a legacy compatibility path for in-turn injected control
    /// inputs (e.g. interrupts). The primary production queue model for user messages
    /// and job results is the thread runtime actor's FIFO inbox.
    #[builder(default = "default_mailbox()")]
    mailbox: Arc<Mutex<ThreadMailbox>>,

    /// Cancellation primitive used to stop this turn.
    #[builder(default)]
    cancellation: TurnCancellation,
}

impl TurnBuilder {
    fn update_shared(mut self, update: impl FnOnce(&mut TurnSharedContext)) -> Self {
        let mut shared = self
            .shared
            .take()
            .map(|shared| (*shared).clone())
            .unwrap_or_default();
        update(&mut shared);
        self.shared = Some(Arc::new(shared));
        self
    }

    /// Set the base message history for this turn.
    pub fn messages(mut self, value: Vec<ChatMessage>) -> Self {
        self = self.update_shared(|shared| {
            Arc::make_mut(&mut shared.state).history = Arc::new(value);
        });
        self
    }

    /// Share an existing history buffer with this turn.
    pub fn shared_messages(mut self, value: Arc<Vec<ChatMessage>>) -> Self {
        self = self.update_shared(|shared| {
            Arc::make_mut(&mut shared.state).history = value;
        });
        self
    }

    /// Set the tool list for this turn.
    pub fn tools(mut self, value: Vec<Arc<dyn NamedTool>>) -> Self {
        self = self.update_shared(|shared| {
            Arc::make_mut(&mut shared.state).tools = Arc::new(value);
        });
        self
    }

    /// Share an existing tool list with this turn.
    pub fn shared_tools(mut self, value: Arc<Vec<Arc<dyn NamedTool>>>) -> Self {
        self = self.update_shared(|shared| {
            Arc::make_mut(&mut shared.state).tools = value;
        });
        self
    }

    /// Set the hook list for this turn.
    pub fn hooks(mut self, value: Vec<Arc<dyn HookHandler>>) -> Self {
        self = self.update_shared(|shared| {
            Arc::make_mut(&mut shared.state).hooks = Arc::new(value);
        });
        self
    }

    /// Share an existing hook list with this turn.
    pub fn shared_hooks(mut self, value: Arc<Vec<Arc<dyn HookHandler>>>) -> Self {
        self = self.update_shared(|shared| {
            Arc::make_mut(&mut shared.state).hooks = value;
        });
        self
    }

    /// Share a prebuilt thread-owned execution context with this turn.
    pub(crate) fn shared(mut self, value: Arc<TurnSharedContext>) -> Self {
        self.shared = Some(value);
        self
    }

    /// Set turn number.
    pub fn turn_number(mut self, value: u32) -> Self {
        self.turn_number = Some(value);
        self
    }

    /// Set thread ID.
    pub fn thread_id(mut self, value: String) -> Self {
        self.thread_id = Some(value);
        self
    }

    /// Set the stable originating thread route for control-plane callbacks.
    pub fn originating_thread_id(mut self, value: ThreadId) -> Self {
        self.originating_thread_id = Some(value);
        self
    }
}

impl std::fmt::Debug for Turn {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Turn")
            .field("id", &self.id)
            .field("turn_number", &self.turn_number)
            .field("thread_id", &self.thread_id)
            .field("messages", &self.shared.state.history.len())
            .field("provider", &self.provider.model_name())
            .field("tools", &self.shared.resolved_tools().len())
            .field("hooks", &self.shared.resolved_hooks().len())
            .field("config", &self.config)
            .finish()
    }
}

impl Turn {
    #[cfg(test)]
    pub(crate) fn shared_snapshot_ptr(&self) -> *const InFlightTurnShared {
        Arc::as_ptr(&self.shared.state)
    }

    fn emit_progress(
        progress_tx: &Option<mpsc::UnboundedSender<TurnProgress>>,
        progress: TurnProgress,
    ) {
        if let Some(progress_tx) = progress_tx {
            let _ = progress_tx.send(progress);
        }
    }

    fn map_approval_progress(event: ThreadEvent) -> Option<TurnProgress> {
        match event {
            ThreadEvent::WaitingForApproval {
                thread_id,
                turn_number,
                request,
            } => Some(TurnProgress::WaitingForApproval {
                thread_id,
                turn_number,
                request,
            }),
            ThreadEvent::ApprovalResolved {
                thread_id,
                turn_number,
                response,
            } => Some(TurnProgress::ApprovalResolved {
                thread_id,
                turn_number,
                response,
            }),
            _ => None,
        }
    }

    fn drain_approval_progress(
        approval_rx: &mut broadcast::Receiver<ThreadEvent>,
        progress_tx: &mpsc::UnboundedSender<TurnProgress>,
    ) {
        loop {
            match approval_rx.try_recv() {
                Ok(event) => {
                    if let Some(progress) = Self::map_approval_progress(event) {
                        let _ = progress_tx.send(progress);
                    }
                }
                Err(broadcast::error::TryRecvError::Empty)
                | Err(broadcast::error::TryRecvError::Closed) => break,
                Err(broadcast::error::TryRecvError::Lagged(_)) => continue,
            }
        }
    }

    async fn execute_internal(
        mut self,
        progress_tx: Option<mpsc::UnboundedSender<TurnProgress>>,
    ) -> Result<TurnOutput, TurnError> {
        tracing::info!(
            thread_id = %self.thread_id,
            turn_number = %self.turn_number,
            tool_count = %self.shared.resolved_tools().len(),
            hook_count = %self.shared.resolved_hooks().len(),
            "Turn execution started"
        );

        let result = self.execute_loop(progress_tx).await;

        tracing::info!(
            thread_id = %self.thread_id,
            turn_number = %self.turn_number,
            result = ?result.as_ref().map(|_| "ok"),
            "Turn execution completed"
        );

        let cancelled = matches!(result, Err(TurnError::Cancelled));

        // Invoke on_turn_complete callback if configured
        if !cancelled
            && let (Some(callback), Some(session_id)) =
                (&self.config.on_turn_complete, &self.session_id)
        {
            callback(*session_id, self.turn_number);
        }

        result
    }

    fn materialize_messages(&self, pending_messages: &[ChatMessage]) -> Vec<ChatMessage> {
        let mut messages = Vec::with_capacity(
            self.shared
                .state
                .history
                .len()
                .saturating_add(pending_messages.len()),
        );
        messages.extend(self.shared.state.history.iter().cloned());
        messages.extend(pending_messages.iter().cloned());
        messages
    }

    /// Execute the turn and return a handle for observing incremental progress.
    pub fn execute_progress(self) -> TurnExecution {
        let mut approval_rx = self.thread_event_tx.subscribe();
        let (progress_tx, progress_rx) = mpsc::unbounded_channel();
        let (result_tx, result_rx) = oneshot::channel();

        tokio::spawn(async move {
            let mut approval_closed = false;
            let turn_fut = self.execute_internal(Some(progress_tx.clone()));
            tokio::pin!(turn_fut);

            let result = loop {
                tokio::select! {
                    result = &mut turn_fut => break result,
                    approval_event = approval_rx.recv(), if !approval_closed => {
                        match approval_event {
                            Ok(event) => {
                                if let Some(progress) = Self::map_approval_progress(event) {
                                    let _ = progress_tx.send(progress);
                                }
                            }
                            Err(broadcast::error::RecvError::Lagged(_)) => {}
                            Err(broadcast::error::RecvError::Closed) => {
                                approval_closed = true;
                            }
                        }
                    }
                }
            };

            Self::drain_approval_progress(&mut approval_rx, &progress_tx);

            match &result {
                Ok(output) => {
                    let _ = progress_tx.send(TurnProgress::Completed(output.clone()));
                }
                Err(error) => {
                    let _ = progress_tx.send(TurnProgress::Failed {
                        error: error.to_string(),
                    });
                }
            }

            let _ = result_tx.send(result);
            drop(progress_tx);
        });

        TurnExecution {
            progress_rx,
            result_rx,
        }
    }

    /// Execute the turn and return the final output.
    pub async fn execute(self) -> Result<TurnOutput, TurnError> {
        self.execute_progress().finish().await
    }

    /// Internal method: trigger hooks and return the action.
    async fn fire_hooks(&self, ctx: &ToolHookContext) -> Result<HookAction, TurnError> {
        for hook in self.shared.resolved_hooks() {
            let action = hook.on_tool_event(ctx).await;

            if let HookAction::Block(reason) = action {
                return Ok(HookAction::Block(reason));
            }

            if !matches!(action, HookAction::Continue) {
                return Ok(action);
            }
        }

        Ok(HookAction::Continue)
    }

    /// Internal method: execute the main LLM -> Tool -> LLM loop.
    ///
    /// This is where the core execution logic lives.
    async fn execute_loop(
        &mut self,
        progress_tx: Option<mpsc::UnboundedSender<TurnProgress>>,
    ) -> Result<TurnOutput, TurnError> {
        let mut pending_messages = std::mem::take(&mut self.pending_messages);
        let max_iterations = self.config.max_iterations.unwrap_or(50);
        let tool_timeout_secs = self.config.tool_timeout_secs.unwrap_or(120);
        let mut token_usage = TokenUsage::default();

        let max_tool_calls = self.config.max_tool_calls;

        for iteration in 0..max_iterations {
            if self.cancellation.is_cancelled() {
                return Err(TurnError::Cancelled);
            }

            let pending_inputs = {
                let mut mailbox = self.mailbox.lock().await;
                mailbox.drain_for_turn()
            };

            for input in pending_inputs {
                let content = input.into_message_text();
                tracing::debug!("injecting control input into turn: {}", content);
                pending_messages.push(ChatMessage::user(&content));
            }

            let available_tools = self.shared.resolved_tools();
            let mut request_messages = self.materialize_messages(&pending_messages);
            if let Some(max) = max_tool_calls
                && !available_tools.is_empty()
            {
                let system_content = format!(
                    "IMPORTANT: You can only call at most {} tool(s) per response. \
                    If you need to call multiple tools, please proceed step by step - \
                    call tools one at a time and wait for the results before calling the next tool.",
                    max
                );
                request_messages.insert(0, ChatMessage::system(system_content));
            }

            tracing::debug!(
                thread_id = %self.thread_id,
                turn_number = %self.turn_number,
                iteration = %iteration,
                max_iterations = %max_iterations,
                message_count = %request_messages.len(),
                "Turn iteration started"
            );

            // Prepare tools from the shared thread-owned context.
            let tools: Vec<ToolDefinition> =
                available_tools.iter().map(|t| t.definition()).collect();

            // Build the request with current messages and tools
            let mut request =
                CompletionRequest::new(request_messages.clone()).with_tools(tools.clone());
            if let Some(max_tokens) = self.agent_record.max_tokens {
                request.max_tokens = Some(max_tokens);
            }
            if let Some(temperature) = self.agent_record.temperature {
                request.temperature = Some(temperature);
            }
            if let Some(thinking_config) = &self.agent_record.thinking_config {
                request.thinking = Some(thinking_config.clone());
            }

            tracing::debug!(
                thread_id = %self.thread_id,
                turn_number = %self.turn_number,
                iteration = %iteration,
                tool_count = %tools.len(),
                message_count = %request_messages.len(),
                "Calling LLM"
            );
            let response = match self.call_llm_streaming(request, progress_tx.clone()).await {
                Ok(StreamingCallOutcome::Completed(response)) => response,
                Ok(StreamingCallOutcome::Failed {
                    partial_response,
                    error,
                }) => {
                    let _ = partial_response;
                    return Err(TurnError::LlmFailed(error));
                }
                Err(error) => return Err(error),
            };
            tracing::debug!(
                thread_id = %self.thread_id,
                turn_number = %self.turn_number,
                iteration = %iteration,
                "LLM call completed"
            );

            // Process response
            let next_action =
                match self.process_finish_reason(response, &mut pending_messages, &mut token_usage)
                {
                    Ok(next_action) => next_action,
                    Err(error) => return Err(error),
                };
            match next_action {
                NextAction::Return(output) => {
                    // Fire TurnEnd hook
                    let ctx = ToolHookContext {
                        event: HookEvent::TurnEnd,
                        tool_name: String::new(),
                        tool_call_id: String::new(),
                        tool_input: serde_json::Value::Null,
                        tool_result: None,
                        error: None,
                        tool_manager: None,
                        thread_event_sender: Some(self.thread_event_tx.clone()),
                        thread_id: Some(self.thread_id.clone()),
                        turn_number: Some(self.turn_number),
                    };
                    let turn_end_action = self.fire_hooks(&ctx).await;

                    let mut output = output;
                    let continue_message = match turn_end_action {
                        Ok(HookAction::ContinueWithMessage(message)) => Some(message),
                        Ok(HookAction::Continue) => None,
                        Ok(HookAction::Block(reason)) => {
                            tracing::warn!(
                                reason = %reason,
                                "TurnEnd hook returned Block (ignored)"
                            );
                            None
                        }
                        Err(error) => {
                            tracing::warn!(
                                error = %error,
                                "TurnEnd hook failed (ignored)"
                            );
                            None
                        }
                    };

                    if let Some(message) = continue_message {
                        pending_messages = std::mem::take(&mut output.appended_messages);
                        pending_messages.push(ChatMessage::user(&message));

                        tracing::debug!(
                            thread_id = %self.thread_id,
                            turn_number = %self.turn_number,
                            iteration = %iteration,
                            "TurnEnd hook requested continuation with injected user message"
                        );
                        continue;
                    }

                    return Ok(output);
                }
                NextAction::ContinueWithTools {
                    tool_calls,
                    content,
                } => {
                    tracing::debug!(
                        thread_id = %self.thread_id,
                        turn_number = %self.turn_number,
                        iteration = %iteration,
                        tool_count = %tool_calls.len(),
                        content_preview = %content.as_ref().map(|c| c.chars().take(100).collect::<String>()).unwrap_or_default(),
                        "Tool calls detected, executing tools"
                    );

                    // Execute tools in parallel
                    let tool_results = tokio::select! {
                        _ = self.cancellation.cancelled() => {
                            return Err(TurnError::Cancelled);
                        }
                        tool_results = self.execute_tools_parallel(tool_calls, tool_timeout_secs, progress_tx.clone()) => tool_results,
                    };

                    tracing::debug!(
                        thread_id = %self.thread_id,
                        turn_number = %self.turn_number,
                        iteration = %iteration,
                        result_count = %tool_results.len(),
                        "Tools executed, adding results to message history"
                    );

                    // Add tool result messages to history
                    for result in tool_results {
                        let (sanitized_content, warning) =
                            sanitize_tool_output(&result.content, &self.config.safety_config);

                        if let Some(w) = &warning {
                            tracing::warn!(
                                thread_id = %self.thread_id,
                                turn_number = %self.turn_number,
                                tool_call_id = %result.tool_call_id,
                                tool_name = %result.name,
                                pattern = %w.pattern,
                                original_len = w.original_len,
                                truncated_len = w.truncated_len,
                                "Tool output was truncated"
                            );
                        }

                        let result_len = sanitized_content.len();
                        let preview = sanitized_content.chars().take(200).collect::<String>();
                        tracing::info!(
                            thread_id = %self.thread_id,
                            turn_number = %self.turn_number,
                            tool_call_id = %result.tool_call_id,
                            tool_name = %result.name,
                            result_len,
                            result_preview = %preview,
                            "Tool result added to history"
                        );
                        pending_messages.push(ChatMessage::tool_result(
                            result.tool_call_id,
                            result.name,
                            sanitized_content,
                        ));
                    }

                    // Continue the loop with updated messages
                }
                NextAction::LengthExceeded => {
                    return Err(TurnError::ContextLengthExceeded(
                        (token_usage.input_tokens + token_usage.output_tokens) as usize,
                    ));
                }
            }
        }

        // Max iterations reached
        Err(TurnError::MaxIterationsReached(max_iterations))
    }

    /// Calls the LLM in streaming mode, accumulating the response.
    ///
    /// Falls back to non-streaming if the provider doesn't support streaming.
    async fn call_llm_streaming(
        &self,
        request: CompletionRequest,
        progress_tx: Option<mpsc::UnboundedSender<TurnProgress>>,
    ) -> Result<StreamingCallOutcome, TurnError> {
        if self.cancellation.is_cancelled() {
            return Err(TurnError::Cancelled);
        }

        match self.provider.stream_complete(request.clone()).await {
            Ok(mut stream) => {
                tracing::debug!(
                    thread_id = %self.thread_id,
                    turn_number = %self.turn_number,
                    "LLM stream started"
                );
                let mut cancel_rx = self.cancellation.subscribe();
                let mut accumulator = StreamingAccumulator::new();
                loop {
                    tokio::select! {
                        change = cancel_rx.changed() => {
                            if change.is_ok() && *cancel_rx.borrow() {
                                return Err(TurnError::Cancelled);
                            }
                        }
                        event_result = stream.next() => {
                            let Some(event_result) = event_result else {
                                break;
                            };

                            let event = match event_result {
                                Ok(event) => event,
                                Err(error) => {
                                    return Ok(StreamingCallOutcome::Failed {
                                        partial_response: accumulator.into_response(),
                                        error,
                                    });
                                }
                            };
                            Self::emit_progress(
                                &progress_tx,
                                TurnProgress::LlmEvent(event.clone()),
                            );
                            if let Err(error) = self.thread_event_tx.send(ThreadEvent::Processing {
                                thread_id: self.thread_id.clone(),
                                turn_number: self.turn_number,
                                event: event.clone(),
                            }) {
                                tracing::warn!(
                                    thread_id = %self.thread_id,
                                    turn_number = %self.turn_number,
                                    error = %error,
                                    "Failed to send Processing event"
                                );
                            }
                            // Forward to stream_tx
                            let _ = self
                                .stream_tx
                                .send(TurnStreamEvent::LlmEvent(event.clone()));
                            accumulator.process(event);
                        }
                    }
                }
                let response = accumulator.into_response();
                tracing::debug!(
                    thread_id = %self.thread_id,
                    turn_number = %self.turn_number,
                    finish_reason = ?response.finish_reason,
                    tool_call_count = %response.tool_calls.len(),
                    "LLM stream completed"
                );
                Ok(StreamingCallOutcome::Completed(response))
            }
            Err(argus_protocol::llm::LlmError::UnsupportedCapability { .. }) => {
                // Fallback to non-streaming
                tracing::debug!("Provider doesn't support streaming, using non-streaming fallback");
                tokio::select! {
                    _ = self.cancellation.cancelled() => Err(TurnError::Cancelled),
                    result = self.provider.complete(request) => result.map(StreamingCallOutcome::Completed).map_err(TurnError::LlmFailed),
                }
            }
            Err(e) => Err(TurnError::LlmFailed(e)),
        }
    }

    /// Processes the LLM response and determines the next action.
    fn process_finish_reason(
        &self,
        response: CompletionResponse,
        pending_messages: &mut Vec<ChatMessage>,
        token_usage: &mut TokenUsage,
    ) -> Result<NextAction, TurnError> {
        let CompletionResponse {
            content,
            reasoning_content,
            tool_calls: response_tool_calls,
            input_tokens,
            output_tokens,
            finish_reason,
            ..
        } = response;

        // Track token usage
        token_usage.input_tokens += input_tokens;
        token_usage.output_tokens += output_tokens;
        token_usage.total_tokens += input_tokens + output_tokens;

        match finish_reason {
            FinishReason::Stop => {
                if content.as_deref().is_some_and(|value| !value.is_empty())
                    || reasoning_content
                        .as_deref()
                        .is_some_and(|value| !value.is_empty())
                {
                    pending_messages.push(ChatMessage::assistant_with_reasoning(
                        content.unwrap_or_default(),
                        reasoning_content,
                    ));
                }

                Ok(NextAction::Return(TurnOutput {
                    appended_messages: std::mem::take(pending_messages),
                    token_usage: token_usage.clone(),
                }))
            }
            FinishReason::ToolUse => {
                // Limit tool calls based on max_tool_calls config
                let tool_calls: Vec<ToolCall> = match self.config.max_tool_calls {
                    Some(max) if response_tool_calls.len() > max as usize => {
                        tracing::debug!(
                            requested = response_tool_calls.len(),
                            max_allowed = max,
                            "Limiting tool calls per iteration"
                        );
                        response_tool_calls.into_iter().take(max as usize).collect()
                    }
                    _ => response_tool_calls,
                };

                // Add assistant message with tool_calls to history
                let assistant_msg = ChatMessage::assistant_with_tool_calls_and_reasoning(
                    content.clone(),
                    tool_calls.clone(),
                    reasoning_content,
                );
                pending_messages.push(assistant_msg);

                Ok(NextAction::ContinueWithTools {
                    tool_calls,
                    content,
                })
            }
            FinishReason::Length => Ok(NextAction::LengthExceeded),
            FinishReason::ContentFilter | FinishReason::Unknown => {
                // If there are actual tool calls, treat as ToolUse (some providers
                // return non-standard finish_reason values when tool calls are present)
                if !response_tool_calls.is_empty() {
                    let tool_calls: Vec<ToolCall> = match self.config.max_tool_calls {
                        Some(max) if response_tool_calls.len() > max as usize => {
                            tracing::debug!(
                                requested = response_tool_calls.len(),
                                max_allowed = max,
                                "Limiting tool calls per iteration"
                            );
                            response_tool_calls.into_iter().take(max as usize).collect()
                        }
                        _ => response_tool_calls,
                    };

                    let assistant_msg = ChatMessage::assistant_with_tool_calls_and_reasoning(
                        content.clone(),
                        tool_calls.clone(),
                        reasoning_content,
                    );
                    pending_messages.push(assistant_msg);

                    Ok(NextAction::ContinueWithTools {
                        tool_calls,
                        content,
                    })
                } else if content.as_deref().is_some_and(|value| !value.is_empty())
                    || reasoning_content
                        .as_deref()
                        .is_some_and(|value| !value.is_empty())
                {
                    pending_messages.push(ChatMessage::assistant_with_reasoning(
                        content.unwrap_or_default(),
                        reasoning_content,
                    ));

                    Ok(NextAction::Return(TurnOutput {
                        appended_messages: std::mem::take(pending_messages),
                        token_usage: token_usage.clone(),
                    }))
                } else {
                    Ok(NextAction::Return(TurnOutput {
                        appended_messages: std::mem::take(pending_messages),
                        token_usage: token_usage.clone(),
                    }))
                }
            }
        }
    }

    /// Executes multiple tool calls in parallel.
    async fn execute_tools_parallel(
        &self,
        tool_calls: Vec<ToolCall>,
        tool_timeout_secs: u64,
        progress_tx: Option<mpsc::UnboundedSender<TurnProgress>>,
    ) -> Vec<ToolExecutionResult> {
        let futures: Vec<_> = tool_calls
            .into_iter()
            .map(|tool_call| {
                self.execute_single_tool(tool_call, tool_timeout_secs, progress_tx.clone())
            })
            .collect();

        join_all(futures).await
    }

    /// Executes a single tool call with hooks and timeout.
    async fn execute_single_tool(
        &self,
        tool_call: ToolCall,
        tool_timeout_secs: u64,
        progress_tx: Option<mpsc::UnboundedSender<TurnProgress>>,
    ) -> ToolExecutionResult {
        let tool_call_id = tool_call.id.clone();
        let tool_name = tool_call.name.clone();
        let tool_input = tool_call.arguments.clone();

        // Find the tool in the shared thread-owned context.
        let tool = self.shared.find_tool(&tool_name);

        // Fire BeforeToolCall hook
        let ctx = ToolHookContext {
            event: HookEvent::BeforeToolCall,
            tool_name: tool_name.clone(),
            tool_call_id: tool_call_id.clone(),
            tool_input: tool_input.clone(),
            tool_result: None,
            error: None,
            tool_manager: tool.clone(),
            thread_event_sender: Some(self.thread_event_tx.clone()),
            thread_id: Some(self.thread_id.clone()),
            turn_number: Some(self.turn_number),
        };

        if let Ok(HookAction::Block(ref reason)) = self.fire_hooks(&ctx).await {
            // Hook blocked the tool call
            let content = format!("Tool call blocked: {}", reason);

            // Fire AfterToolCall hook with error
            let after_ctx = ToolHookContext {
                event: HookEvent::AfterToolCall,
                tool_name: tool_name.clone(),
                tool_call_id: tool_call_id.clone(),
                tool_input,
                tool_result: None,
                error: Some(reason.clone()),
                tool_manager: None,
                thread_event_sender: Some(self.thread_event_tx.clone()),
                thread_id: Some(self.thread_id.clone()),
                turn_number: Some(self.turn_number),
            };
            let _ = self.fire_hooks(&after_ctx).await;

            return ToolExecutionResult {
                tool_call_id,
                name: tool_name,
                content,
            };
        }

        // Send ToolStarted events
        if let Err(e) = self.thread_event_tx.send(ThreadEvent::ToolStarted {
            thread_id: self.thread_id.clone(),
            turn_number: self.turn_number,
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            arguments: tool_input.clone(),
        }) {
            tracing::warn!(
                thread_id = %self.thread_id,
                turn_number = %self.turn_number,
                tool_name = %tool_name,
                error = %e,
                "Failed to send ToolStarted event"
            );
        }
        Self::emit_progress(
            &progress_tx,
            TurnProgress::ToolStarted {
                tool_call_id: tool_call_id.clone(),
                tool_name: tool_name.clone(),
                arguments: tool_input.clone(),
            },
        );
        let _ = self.stream_tx.send(TurnStreamEvent::ToolStarted {
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            arguments: tool_input.clone(),
        });

        // Execute the tool with timeout
        let timeout_duration = std::time::Duration::from_secs(tool_timeout_secs);
        set_current_agent_id(self.agent_record.id);
        let start_time = std::time::Instant::now();
        let execute_result = {
            let execute_future = async {
                if let Some(tool) = tool {
                    tracing::debug!(
                        thread_id = %self.thread_id,
                        turn_number = %self.turn_number,
                        tool_call_id = %tool_call_id,
                        tool_name = %tool_name,
                        "Executing tool"
                    );
                    let ctx = Arc::new(ToolExecutionContext {
                        thread_id: self.originating_thread_id,
                        agent_id: Some(self.agent_record.id),
                        pipe_tx: self.thread_event_tx.clone(),
                        control_tx: self.control_tx.clone(),
                    });
                    tool.execute(tool_input.clone(), ctx).await
                } else {
                    tracing::error!(
                        thread_id = %self.thread_id,
                        turn_number = %self.turn_number,
                        tool_call_id = %tool_call_id,
                        tool_name = %tool_name,
                        available_tools = ?self.shared.resolved_tools().iter().map(|t| t.name()).collect::<Vec<_>>(),
                        "Tool not found in registry"
                    );
                    Err(argus_protocol::tool::ToolError::NotFound {
                        id: tool_name.clone(),
                    })
                }
            };
            timeout(timeout_duration, execute_future).await
        };
        clear_current_agent_id();

        let result = match execute_result {
            Ok(Ok(value)) => {
                tracing::info!(
                    thread_id = %self.thread_id,
                    turn_number = %self.turn_number,
                    tool_call_id = %tool_call_id,
                    tool_name = %tool_name,
                    result_preview = %value.to_string().chars().take(200).collect::<String>(),
                    "Tool executed successfully"
                );
                Ok(value)
            }
            Ok(Err(e)) => {
                tracing::warn!(
                    thread_id = %self.thread_id,
                    turn_number = %self.turn_number,
                    tool_call_id = %tool_call_id,
                    tool_name = %tool_name,
                    error = %e,
                    "Tool execution returned error"
                );
                Err(e.to_string())
            }
            Err(Elapsed { .. }) => {
                tracing::error!(
                    thread_id = %self.thread_id,
                    turn_number = %self.turn_number,
                    tool_call_id = %tool_call_id,
                    tool_name = %tool_name,
                    timeout_secs = %tool_timeout_secs,
                    "Tool execution timed out"
                );
                Err(format!(
                    "Tool execution timed out after {}s",
                    tool_timeout_secs
                ))
            }
        };

        // Send ToolCompleted events
        let event_result = match &result {
            Ok(value) => Ok(value.clone()),
            Err(e) => Err(e.clone()),
        };
        if let Err(e) = self.thread_event_tx.send(ThreadEvent::ToolCompleted {
            thread_id: self.thread_id.clone(),
            turn_number: self.turn_number,
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            result: event_result.clone(),
        }) {
            tracing::warn!(
                thread_id = %self.thread_id,
                turn_number = %self.turn_number,
                tool_name = %tool_name,
                error = %e,
                "Failed to send ToolCompleted event"
            );
        }
        Self::emit_progress(
            &progress_tx,
            TurnProgress::ToolCompleted {
                tool_call_id: tool_call_id.clone(),
                tool_name: tool_name.clone(),
                result: result.clone(),
            },
        );
        let _ = self.stream_tx.send(TurnStreamEvent::ToolCompleted {
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            result: event_result,
        });

        // Fire AfterToolCall hook
        let (tool_result, error) = match &result {
            Ok(value) => (Some(value.clone()), None),
            Err(e) => (None, Some(e.clone())),
        };
        let ctx = ToolHookContext {
            event: HookEvent::AfterToolCall,
            tool_name: tool_name.clone(),
            tool_call_id: tool_call_id.clone(),
            tool_input,
            tool_result,
            error,
            tool_manager: None,
            thread_event_sender: Some(self.thread_event_tx.clone()),
            thread_id: Some(self.thread_id.clone()),
            turn_number: Some(self.turn_number),
        };
        let _ = self.fire_hooks(&ctx).await;

        // Convert result to string content.
        let _duration_ms = start_time.elapsed().as_millis() as u64;
        let content = match &result {
            Ok(value) => serde_json::to_string(value).unwrap_or_else(|e| {
                format!("{{\"error\": \"Failed to serialize result: {}\"}}", e)
            }),
            Err(e) => format!("{{\"error\": \"{}\"}}", e),
        };

        ToolExecutionResult {
            tool_call_id,
            name: tool_name,
            content,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;
    use std::sync::{Arc, Mutex};

    use crate::compact::{CompactResult, Compactor};
    use crate::error::CompactError;
    use crate::thread::ThreadBuilder;
    use argus_protocol::llm::{CompletionRequest, CompletionResponse, LlmError};
    use argus_protocol::tool::{NamedTool, ToolError};
    use argus_protocol::{
        AgentId, AgentType, ApprovalDecision, ApprovalRequest, ApprovalResponse, HookAction,
        HookEvent, HookHandler, HookRegistry, ProviderId, RiskLevel, SessionId, ThreadEvent,
        TokenUsage, ToolExecutionContext, ToolHookContext,
    };
    use async_trait::async_trait;
    use rust_decimal::Decimal;
    use tokio::sync::{Mutex as TokioMutex, Notify, broadcast, oneshot};

    #[test]
    fn test_generate_turn_id() {
        let id = generate_turn_id("thread-123", 5);
        assert_eq!(id, "thread-123-turn-5");
    }

    #[test]
    fn test_turn_builder_requires_turn_number_and_thread_id() {
        // This test verifies the builder API
        // Actual builder validation will be done in integration tests
    }

    #[test]
    fn test_turn_debug_format() {
        // Create channels for testing
        let (stream_tx, _): (broadcast::Sender<TurnStreamEvent>, _) = broadcast::channel(256);
        let (thread_event_tx, _): (broadcast::Sender<ThreadEvent>, _) = broadcast::channel(256);

        // Note: We can't easily test this without a mock provider
        // This is just a placeholder test to verify channel creation works
        let _ = (stream_tx, thread_event_tx);
    }

    #[derive(Debug)]
    struct SequencedProvider {
        responses: Mutex<Vec<CompletionResponse>>,
    }

    impl SequencedProvider {
        fn new(responses: Vec<CompletionResponse>) -> Self {
            Self {
                responses: Mutex::new(responses),
            }
        }
    }

    #[async_trait]
    impl LlmProvider for SequencedProvider {
        fn model_name(&self) -> &str {
            "sequenced"
        }

        fn cost_per_token(&self) -> (Decimal, Decimal) {
            (Decimal::ZERO, Decimal::ZERO)
        }

        async fn complete(
            &self,
            _request: CompletionRequest,
        ) -> Result<CompletionResponse, LlmError> {
            let mut responses = self.responses.lock().unwrap();
            if responses.is_empty() {
                return Ok(CompletionResponse {
                    content: Some("done".to_string()),
                    reasoning_content: None,
                    tool_calls: Vec::new(),
                    input_tokens: 1,
                    output_tokens: 1,
                    finish_reason: FinishReason::Stop,
                    cache_read_input_tokens: 0,
                    cache_creation_input_tokens: 0,
                });
            }
            Ok(responses.remove(0))
        }
    }

    #[derive(Debug)]
    struct BlockingFirstResponseProvider {
        responses: Mutex<Vec<CompletionResponse>>,
        first_call_started: Mutex<Option<oneshot::Sender<()>>>,
        release_first_call: Arc<Notify>,
        gate_first_call: Mutex<bool>,
    }

    impl BlockingFirstResponseProvider {
        fn new(
            responses: Vec<CompletionResponse>,
            first_call_started: oneshot::Sender<()>,
            release_first_call: Arc<Notify>,
        ) -> Self {
            Self {
                responses: Mutex::new(responses),
                first_call_started: Mutex::new(Some(first_call_started)),
                release_first_call,
                gate_first_call: Mutex::new(true),
            }
        }
    }

    #[async_trait]
    impl LlmProvider for BlockingFirstResponseProvider {
        fn model_name(&self) -> &str {
            "blocking-first"
        }

        fn cost_per_token(&self) -> (Decimal, Decimal) {
            (Decimal::ZERO, Decimal::ZERO)
        }

        async fn complete(
            &self,
            _request: CompletionRequest,
        ) -> Result<CompletionResponse, LlmError> {
            let should_gate = {
                let mut gate_first_call = self.gate_first_call.lock().unwrap();
                let should_gate = *gate_first_call;
                *gate_first_call = false;
                should_gate
            };

            if should_gate {
                if let Some(sender) = self.first_call_started.lock().unwrap().take() {
                    let _ = sender.send(());
                }
                self.release_first_call.notified().await;
            }

            let mut responses = self.responses.lock().unwrap();
            Ok(responses.remove(0))
        }
    }

    struct EchoTool;

    #[async_trait]
    impl NamedTool for EchoTool {
        fn name(&self) -> &str {
            "echo"
        }

        fn definition(&self) -> argus_protocol::llm::ToolDefinition {
            argus_protocol::llm::ToolDefinition {
                name: "echo".to_string(),
                description: "Echo back the input message".to_string(),
                parameters: serde_json::json!({
                    "type": "object",
                    "properties": {
                        "message": {
                            "type": "string",
                        }
                    },
                    "required": ["message"]
                }),
            }
        }

        async fn execute(
            &self,
            args: serde_json::Value,
            _ctx: Arc<ToolExecutionContext>,
        ) -> Result<serde_json::Value, ToolError> {
            let message = args
                .get("message")
                .and_then(|v| v.as_str())
                .ok_or_else(|| ToolError::ExecutionFailed {
                    tool_name: "echo".to_string(),
                    reason: "Missing 'message' parameter".to_string(),
                })?;

            Ok(serde_json::json!({ "echoed": message }))
        }
    }

    struct VersionedTool {
        version: &'static str,
    }

    #[async_trait]
    impl NamedTool for VersionedTool {
        fn name(&self) -> &str {
            "late_echo"
        }

        fn definition(&self) -> argus_protocol::llm::ToolDefinition {
            argus_protocol::llm::ToolDefinition {
                name: "late_echo".to_string(),
                description: format!("Return the current tool version {}", self.version),
                parameters: serde_json::json!({
                    "type": "object",
                    "properties": {}
                }),
            }
        }

        async fn execute(
            &self,
            _args: serde_json::Value,
            _ctx: Arc<ToolExecutionContext>,
        ) -> Result<serde_json::Value, ToolError> {
            Ok(serde_json::json!({ "version": self.version }))
        }
    }

    struct HangingStreamingProvider;

    #[async_trait]
    impl LlmProvider for HangingStreamingProvider {
        fn model_name(&self) -> &str {
            "hanging"
        }

        fn cost_per_token(&self) -> (Decimal, Decimal) {
            (Decimal::ZERO, Decimal::ZERO)
        }

        async fn complete(
            &self,
            _request: CompletionRequest,
        ) -> Result<CompletionResponse, LlmError> {
            Err(LlmError::UnsupportedCapability {
                provider: "hanging".to_string(),
                capability: "complete".to_string(),
            })
        }

        async fn stream_complete(
            &self,
            _request: CompletionRequest,
        ) -> Result<argus_protocol::llm::LlmEventStream, LlmError> {
            let stream = futures_util::stream::unfold(0usize, |state| async move {
                tokio::time::sleep(std::time::Duration::from_millis(50)).await;
                Some((
                    Ok(argus_protocol::llm::LlmStreamEvent::ContentDelta {
                        delta: format!("tick-{}", state),
                    }),
                    state.saturating_add(1),
                ))
            });

            Ok(Box::pin(stream))
        }
    }

    struct ContinueOnceTurnEndHook {
        used: Mutex<bool>,
    }

    impl ContinueOnceTurnEndHook {
        fn new() -> Self {
            Self {
                used: Mutex::new(false),
            }
        }
    }

    #[async_trait]
    impl HookHandler for ContinueOnceTurnEndHook {
        async fn on_tool_event(&self, ctx: &ToolHookContext) -> HookAction {
            if ctx.event == HookEvent::TurnEnd {
                let mut used = self.used.lock().unwrap();
                if !*used {
                    *used = true;
                    return HookAction::ContinueWithMessage("continue".to_string());
                }
            }
            HookAction::Continue
        }
    }

    struct AlwaysContinueTurnEndHook;

    #[async_trait]
    impl HookHandler for AlwaysContinueTurnEndHook {
        async fn on_tool_event(&self, ctx: &ToolHookContext) -> HookAction {
            if ctx.event == HookEvent::TurnEnd {
                return HookAction::ContinueWithMessage("continue".to_string());
            }
            HookAction::Continue
        }
    }

    struct NoopCompactor;

    #[async_trait]
    impl Compactor for NoopCompactor {
        async fn compact(
            &self,
            _provider: &dyn LlmProvider,
            _messages: &[ChatMessage],
            _token_count: u32,
        ) -> Result<Option<CompactResult>, CompactError> {
            Ok(None)
        }

        fn name(&self) -> &'static str {
            "noop"
        }
    }

    struct BlockingApprovalHook {
        gate: Arc<TokioMutex<Option<oneshot::Receiver<()>>>>,
    }

    impl BlockingApprovalHook {
        fn new(gate: oneshot::Receiver<()>) -> Self {
            Self {
                gate: Arc::new(TokioMutex::new(Some(gate))),
            }
        }
    }

    #[async_trait]
    impl HookHandler for BlockingApprovalHook {
        async fn on_tool_event(&self, ctx: &ToolHookContext) -> HookAction {
            if ctx.event != HookEvent::BeforeToolCall || ctx.tool_name != "echo" {
                return HookAction::Continue;
            }

            let request = ApprovalRequest::new(
                "test-agent".to_string(),
                ctx.tool_name.clone(),
                "pause for approval".to_string(),
                60,
                RiskLevel::High,
            );

            if let (Some(sender), Some(thread_id), Some(turn_number)) = (
                &ctx.thread_event_sender,
                ctx.thread_id.clone(),
                ctx.turn_number,
            ) {
                let _ = sender.send(ThreadEvent::WaitingForApproval {
                    thread_id,
                    turn_number,
                    request: request.clone(),
                });
            }

            if let Some(gate) = self.gate.lock().await.take() {
                let _ = gate.await;
            }

            if let (Some(sender), Some(thread_id), Some(turn_number)) = (
                &ctx.thread_event_sender,
                ctx.thread_id.clone(),
                ctx.turn_number,
            ) {
                let response = ApprovalResponse {
                    request_id: request.id,
                    decision: ApprovalDecision::Approved,
                    decided_at: Utc::now(),
                    decided_by: Some("test".to_string()),
                };
                let _ = sender.send(ThreadEvent::ApprovalResolved {
                    thread_id,
                    turn_number,
                    response,
                });
            }

            HookAction::Continue
        }
    }

    fn make_agent_record() -> Arc<AgentRecord> {
        Arc::new(AgentRecord {
            id: AgentId::new(1),
            display_name: "Test Agent".to_string(),
            description: "A test agent".to_string(),
            version: "1.0.0".to_string(),
            provider_id: Some(ProviderId::new(1)),
            model_id: None,
            system_prompt: "You are a test agent.".to_string(),
            tool_names: vec![],
            max_tokens: None,
            temperature: None,
            thinking_config: None,
            parent_agent_id: None,
            agent_type: AgentType::Standard,
        })
    }

    fn make_agent_record_with_tools(tool_names: Vec<&str>) -> Arc<AgentRecord> {
        Arc::new(AgentRecord {
            tool_names: tool_names.into_iter().map(str::to_string).collect(),
            ..(*make_agent_record()).clone()
        })
    }

    fn make_turn(
        provider: Arc<dyn LlmProvider>,
        hooks: Vec<Arc<dyn HookHandler>>,
        max_iterations: u32,
    ) -> Turn {
        let (stream_tx, _stream_rx): (broadcast::Sender<TurnStreamEvent>, _) =
            broadcast::channel(256);
        let (thread_event_tx, _thread_event_rx): (broadcast::Sender<ThreadEvent>, _) =
            broadcast::channel(256);

        TurnBuilder::default()
            .turn_number(1)
            .thread_id("thread-test".to_string())
            .messages(vec![ChatMessage::user("start")])
            .provider(provider)
            .hooks(hooks)
            .config(TurnConfig {
                max_iterations: Some(max_iterations),
                ..TurnConfig::default()
            })
            .agent_record(make_agent_record())
            .stream_tx(stream_tx)
            .thread_event_tx(thread_event_tx)
            .build()
            .expect("turn should build")
    }

    fn versioned_tool_description(turn: &Turn) -> Option<String> {
        turn.shared
            .resolved_tools()
            .into_iter()
            .find(|tool| tool.name() == "late_echo")
            .map(|tool| tool.definition().description)
    }

    fn resolved_hook_count(turn: &Turn) -> usize {
        turn.shared.resolved_hooks().len()
    }

    fn build_thread_with_live_sources(
        provider: Arc<dyn LlmProvider>,
        agent_record: Arc<AgentRecord>,
        tool_manager: Arc<argus_tool::ToolManager>,
        hooks: Arc<HookRegistry>,
    ) -> crate::thread::Thread {
        let compactor: Arc<dyn Compactor> = Arc::new(NoopCompactor);
        ThreadBuilder::new()
            .provider(provider)
            .compactor(compactor)
            .agent_record(agent_record)
            .session_id(SessionId::new())
            .tool_manager(tool_manager)
            .hooks(hooks)
            .build()
            .expect("thread should build")
    }

    #[tokio::test]
    async fn shared_history_turn_reuses_thread_owned_tool_and_hook_state() {
        let provider = Arc::new(SequencedProvider::new(vec![]));
        let tool_manager = Arc::new(argus_tool::ToolManager::new());
        tool_manager.register(Arc::new(VersionedTool { version: "v1" }));
        let hooks = Arc::new(HookRegistry::new());
        let mut thread = build_thread_with_live_sources(
            provider,
            make_agent_record_with_tools(vec!["late_echo"]),
            Arc::clone(&tool_manager),
            Arc::clone(&hooks),
        );

        let first_turn = thread
            .begin_turn("first".to_string(), None, TurnCancellation::default())
            .await
            .expect("first turn should build");
        let first_tool_description =
            versioned_tool_description(&first_turn).expect("first turn should resolve tool");
        let first_hook_count = resolved_hook_count(&first_turn);

        thread
            .finish_turn(Ok(TurnOutput {
                appended_messages: vec![ChatMessage::assistant("done")],
                token_usage: TokenUsage::default(),
            }))
            .expect("first turn should settle");

        tool_manager.register(Arc::new(VersionedTool { version: "v2" }));
        hooks.register(HookEvent::TurnEnd, Arc::new(ContinueOnceTurnEndHook::new()));

        let second_turn = thread
            .begin_turn("second".to_string(), None, TurnCancellation::default())
            .await
            .expect("second turn should build");

        let second_tool_description =
            versioned_tool_description(&second_turn).expect("second turn should resolve tool");
        let second_hook_count = resolved_hook_count(&second_turn);

        assert!(first_tool_description.contains("v1"));
        assert!(second_tool_description.contains("v2"));
        assert!(second_hook_count > first_hook_count);
    }

    #[tokio::test]
    async fn shared_history_turn_sees_late_tool_overwrite_after_thread_creation() {
        let provider = Arc::new(SequencedProvider::new(vec![
            CompletionResponse {
                content: Some("tool call".to_string()),
                reasoning_content: None,
                tool_calls: vec![argus_protocol::llm::ToolCall {
                    id: "call-late-tool".to_string(),
                    name: "late_echo".to_string(),
                    arguments: serde_json::json!({}),
                }],
                input_tokens: 1,
                output_tokens: 1,
                finish_reason: FinishReason::ToolUse,
                cache_read_input_tokens: 0,
                cache_creation_input_tokens: 0,
            },
            CompletionResponse {
                content: Some("done".to_string()),
                reasoning_content: None,
                tool_calls: Vec::new(),
                input_tokens: 1,
                output_tokens: 1,
                finish_reason: FinishReason::Stop,
                cache_read_input_tokens: 0,
                cache_creation_input_tokens: 0,
            },
        ]));
        let tool_manager = Arc::new(argus_tool::ToolManager::new());
        tool_manager.register(Arc::new(VersionedTool { version: "v1" }));
        let hooks = Arc::new(HookRegistry::new());
        let mut thread = build_thread_with_live_sources(
            provider,
            make_agent_record_with_tools(vec!["late_echo"]),
            Arc::clone(&tool_manager),
            hooks,
        );

        tool_manager.register(Arc::new(VersionedTool { version: "v2" }));

        let output = thread
            .begin_turn("start".to_string(), None, TurnCancellation::default())
            .await
            .expect("turn should build")
            .execute()
            .await
            .expect("turn should execute");

        let tool_results = output
            .appended_messages
            .iter()
            .filter(|message| message.role == argus_protocol::llm::Role::Tool)
            .map(|message| message.content.clone())
            .collect::<Vec<_>>();

        assert_eq!(tool_results, vec![r#"{"version":"v2"}"#.to_string()]);
    }

    #[tokio::test]
    async fn shared_history_turn_sees_late_hook_registration_after_thread_creation() {
        let provider = Arc::new(SequencedProvider::new(vec![
            CompletionResponse {
                content: Some("first".to_string()),
                reasoning_content: None,
                tool_calls: Vec::new(),
                input_tokens: 1,
                output_tokens: 1,
                finish_reason: FinishReason::Stop,
                cache_read_input_tokens: 0,
                cache_creation_input_tokens: 0,
            },
            CompletionResponse {
                content: Some("second".to_string()),
                reasoning_content: None,
                tool_calls: Vec::new(),
                input_tokens: 1,
                output_tokens: 1,
                finish_reason: FinishReason::Stop,
                cache_read_input_tokens: 0,
                cache_creation_input_tokens: 0,
            },
        ]));
        let tool_manager = Arc::new(argus_tool::ToolManager::new());
        let hooks = Arc::new(HookRegistry::new());
        let mut thread = build_thread_with_live_sources(
            provider,
            make_agent_record(),
            tool_manager,
            Arc::clone(&hooks),
        );

        hooks.register(HookEvent::TurnEnd, Arc::new(ContinueOnceTurnEndHook::new()));

        let output = thread
            .begin_turn("start".to_string(), None, TurnCancellation::default())
            .await
            .expect("turn should build")
            .execute()
            .await
            .expect("turn should execute");

        assert!(
            output
                .appended_messages
                .iter()
                .any(|message| message.content == "second")
        );
    }

    #[tokio::test]
    async fn shared_history_active_turn_does_not_see_late_hook_registration() {
        let (first_call_started_tx, first_call_started_rx) = oneshot::channel();
        let release_first_call = Arc::new(Notify::new());
        let provider = Arc::new(BlockingFirstResponseProvider::new(
            vec![
                CompletionResponse {
                    content: Some("first".to_string()),
                    reasoning_content: None,
                    tool_calls: Vec::new(),
                    input_tokens: 1,
                    output_tokens: 1,
                    finish_reason: FinishReason::Stop,
                    cache_read_input_tokens: 0,
                    cache_creation_input_tokens: 0,
                },
                CompletionResponse {
                    content: Some("second".to_string()),
                    reasoning_content: None,
                    tool_calls: Vec::new(),
                    input_tokens: 1,
                    output_tokens: 1,
                    finish_reason: FinishReason::Stop,
                    cache_read_input_tokens: 0,
                    cache_creation_input_tokens: 0,
                },
            ],
            first_call_started_tx,
            Arc::clone(&release_first_call),
        ));
        let tool_manager = Arc::new(argus_tool::ToolManager::new());
        let hooks = Arc::new(HookRegistry::new());
        let mut thread = build_thread_with_live_sources(
            provider,
            make_agent_record(),
            tool_manager,
            Arc::clone(&hooks),
        );

        let turn = thread
            .begin_turn("start".to_string(), None, TurnCancellation::default())
            .await
            .expect("turn should build");
        let execution = tokio::spawn(async move { turn.execute().await });

        first_call_started_rx
            .await
            .expect("turn should start the first provider call");

        hooks.register(HookEvent::TurnEnd, Arc::new(ContinueOnceTurnEndHook::new()));
        release_first_call.notify_waiters();

        let output = execution
            .await
            .expect("turn task should complete")
            .expect("turn should execute");

        assert!(
            output
                .appended_messages
                .iter()
                .all(|message| message.content != "second")
        );
    }

    #[tokio::test]
    async fn turn_end_continue_with_message_triggers_next_iteration() {
        let provider = Arc::new(SequencedProvider::new(vec![
            CompletionResponse {
                content: Some("first".to_string()),
                reasoning_content: None,
                tool_calls: Vec::new(),
                input_tokens: 1,
                output_tokens: 1,
                finish_reason: FinishReason::Stop,
                cache_read_input_tokens: 0,
                cache_creation_input_tokens: 0,
            },
            CompletionResponse {
                content: Some("second".to_string()),
                reasoning_content: None,
                tool_calls: Vec::new(),
                input_tokens: 1,
                output_tokens: 1,
                finish_reason: FinishReason::Stop,
                cache_read_input_tokens: 0,
                cache_creation_input_tokens: 0,
            },
        ]));

        let turn = make_turn(provider, vec![Arc::new(ContinueOnceTurnEndHook::new())], 5);
        let output = turn.execute().await.expect("turn should succeed");

        assert!(
            output
                .appended_messages
                .iter()
                .any(|m| m.content == "first")
        );
        assert!(
            output
                .appended_messages
                .iter()
                .any(|m| m.content == "continue")
        );
        assert!(
            output
                .appended_messages
                .iter()
                .any(|m| m.content == "second")
        );
    }

    #[tokio::test]
    async fn turn_end_always_continue_hits_max_iterations() {
        let provider = Arc::new(SequencedProvider::new(vec![CompletionResponse {
            content: Some("loop".to_string()),
            reasoning_content: None,
            tool_calls: Vec::new(),
            input_tokens: 1,
            output_tokens: 1,
            finish_reason: FinishReason::Stop,
            cache_read_input_tokens: 0,
            cache_creation_input_tokens: 0,
        }]));

        let turn = make_turn(provider, vec![Arc::new(AlwaysContinueTurnEndHook)], 2);
        let result = turn.execute().await;

        assert!(matches!(result, Err(TurnError::MaxIterationsReached(2))));
    }

    #[tokio::test]
    async fn turn_progress_normal_completion_emits_terminal_completed_progress() {
        let provider = Arc::new(SequencedProvider::new(vec![CompletionResponse {
            content: Some("Hello, progress!".to_string()),
            reasoning_content: None,
            tool_calls: Vec::new(),
            input_tokens: 1,
            output_tokens: 1,
            finish_reason: FinishReason::Stop,
            cache_read_input_tokens: 0,
            cache_creation_input_tokens: 0,
        }]));
        let turn = make_turn(provider, vec![], 5);

        let execution = turn.execute_progress().collect().await;
        let output = execution.result.expect("turn should succeed");

        assert_eq!(output.appended_messages.len(), 1);
        assert_eq!(output.appended_messages[0].content, "Hello, progress!");
        assert!(matches!(
            execution.progress.last(),
            Some(TurnProgress::Completed(final_output))
                if final_output.appended_messages.len() == 1
                    && final_output.appended_messages[0].content == "Hello, progress!"
        ));
    }

    #[tokio::test]
    async fn turn_progress_tool_progress_emission_includes_tool_started_and_completed() {
        let provider = Arc::new(SequencedProvider::new(vec![
            CompletionResponse {
                content: Some("first".to_string()),
                reasoning_content: None,
                tool_calls: vec![argus_protocol::llm::ToolCall {
                    id: "call-123".to_string(),
                    name: "echo".to_string(),
                    arguments: serde_json::json!({"message": "test message"}),
                }],
                input_tokens: 1,
                output_tokens: 1,
                finish_reason: FinishReason::ToolUse,
                cache_read_input_tokens: 0,
                cache_creation_input_tokens: 0,
            },
            CompletionResponse {
                content: Some("done".to_string()),
                reasoning_content: None,
                tool_calls: Vec::new(),
                input_tokens: 1,
                output_tokens: 1,
                finish_reason: FinishReason::Stop,
                cache_read_input_tokens: 0,
                cache_creation_input_tokens: 0,
            },
        ]));

        let (stream_tx, _) = broadcast::channel(256);
        let (thread_event_tx, _) = broadcast::channel(256);
        let turn = TurnBuilder::default()
            .turn_number(1)
            .thread_id("thread-test".to_string())
            .messages(vec![ChatMessage::user("start")])
            .provider(provider)
            .tools(vec![Arc::new(EchoTool)])
            .hooks(vec![])
            .config(TurnConfig {
                max_iterations: Some(5),
                ..TurnConfig::default()
            })
            .agent_record(make_agent_record())
            .stream_tx(stream_tx)
            .thread_event_tx(thread_event_tx)
            .build()
            .expect("turn should build");

        let execution = turn.execute_progress().collect().await;
        assert!(execution.result.is_ok());
        assert!(execution
            .progress
            .iter()
            .any(|item| matches!(item, TurnProgress::ToolStarted { tool_name, .. } if tool_name == "echo")));
        assert!(execution
            .progress
            .iter()
            .any(|item| matches!(item, TurnProgress::ToolCompleted { tool_name, .. } if tool_name == "echo")));
    }

    #[tokio::test]
    async fn turn_progress_cancellation_returns_failed_progress() {
        let provider = Arc::new(HangingStreamingProvider);
        let cancellation = TurnCancellation::new();

        let (stream_tx, _) = broadcast::channel(256);
        let (thread_event_tx, _) = broadcast::channel(256);

        let turn = TurnBuilder::default()
            .turn_number(1)
            .thread_id("test-thread".to_string())
            .messages(vec![ChatMessage::user("Hello")])
            .provider(provider)
            .agent_record(Arc::new(AgentRecord::default()))
            .tools(vec![])
            .hooks(vec![])
            .config(TurnConfig::default())
            .stream_tx(stream_tx)
            .thread_event_tx(thread_event_tx)
            .cancellation(cancellation.clone())
            .build()
            .expect("turn should build");

        let mut execution = turn.execute_progress();
        let first_progress =
            tokio::time::timeout(std::time::Duration::from_millis(200), execution.recv())
                .await
                .expect("progress should arrive before turn completion")
                .expect("turn should emit an initial progress item");
        assert!(matches!(
            first_progress,
            TurnProgress::LlmEvent(LlmStreamEvent::ContentDelta { .. })
        ));

        cancellation.cancel();
        let mut saw_failed_progress = false;
        loop {
            let progress =
                tokio::time::timeout(std::time::Duration::from_millis(500), execution.recv())
                    .await
                    .expect("turn should terminate quickly after cancellation");
            let Some(progress) = progress else {
                break;
            };
            if matches!(&progress, TurnProgress::Failed { error } if error.contains("cancelled")) {
                saw_failed_progress = true;
            }
        }

        let result = execution.finish().await;
        assert!(matches!(result, Err(TurnError::Cancelled)));
        assert!(saw_failed_progress);
    }

    #[tokio::test]
    async fn turn_progress_approval_pause_and_resume_emits_waiting_and_resolved_progress() {
        let provider = Arc::new(SequencedProvider::new(vec![
            CompletionResponse {
                content: Some("first".to_string()),
                reasoning_content: None,
                tool_calls: vec![argus_protocol::llm::ToolCall {
                    id: "call-approval".to_string(),
                    name: "echo".to_string(),
                    arguments: serde_json::json!({"message": "approval test"}),
                }],
                input_tokens: 1,
                output_tokens: 1,
                finish_reason: FinishReason::ToolUse,
                cache_read_input_tokens: 0,
                cache_creation_input_tokens: 0,
            },
            CompletionResponse {
                content: Some("done".to_string()),
                reasoning_content: None,
                tool_calls: Vec::new(),
                input_tokens: 1,
                output_tokens: 1,
                finish_reason: FinishReason::Stop,
                cache_read_input_tokens: 0,
                cache_creation_input_tokens: 0,
            },
        ]));

        let (resume_tx, resume_rx) = oneshot::channel();
        let approval_hook = Arc::new(BlockingApprovalHook::new(resume_rx));
        let (stream_tx, _) = broadcast::channel(256);
        let (thread_event_tx, mut thread_event_rx) = broadcast::channel(256);

        let turn = TurnBuilder::default()
            .turn_number(1)
            .thread_id("thread-test".to_string())
            .messages(vec![ChatMessage::user("start")])
            .provider(provider)
            .tools(vec![Arc::new(EchoTool)])
            .hooks(vec![approval_hook])
            .config(TurnConfig {
                max_iterations: Some(5),
                ..TurnConfig::default()
            })
            .agent_record(make_agent_record())
            .stream_tx(stream_tx)
            .thread_event_tx(thread_event_tx)
            .build()
            .expect("turn should build");

        let execution = turn.execute_progress();

        let mut saw_waiting = false;
        while !saw_waiting {
            match tokio::time::timeout(std::time::Duration::from_secs(1), thread_event_rx.recv())
                .await
                .expect("should receive approval event in time")
            {
                Ok(ThreadEvent::WaitingForApproval { .. }) => {
                    saw_waiting = true;
                }
                Ok(_) => {}
                Err(broadcast::error::RecvError::Lagged(_)) => {}
                Err(broadcast::error::RecvError::Closed) => break,
            }
        }

        resume_tx
            .send(())
            .expect("approval hook should still be waiting");

        let execution =
            tokio::time::timeout(std::time::Duration::from_secs(2), execution.collect())
                .await
                .expect("turn should resume and finish");

        assert!(execution.result.is_ok());
        assert!(
            execution
                .progress
                .iter()
                .any(|item| matches!(item, TurnProgress::WaitingForApproval { .. }))
        );
        assert!(
            execution
                .progress
                .iter()
                .any(|item| matches!(item, TurnProgress::ApprovalResolved { .. }))
        );
    }
}
