//! Turn struct for managing turn lifecycle and execution.
//!
//! This module defines the `Turn` struct, which owns its resources (tools and hooks)
//! and is responsible only for execution logic. Construction is handled by `TurnBuilder`
//! (auto-generated by `derive_builder`) or by the Thread layer.

use std::sync::Arc;

use derive_builder::Builder;
use futures_util::{StreamExt, future::join_all};
use tokio::sync::{Mutex, broadcast, mpsc, watch};
use tokio::time::{error::Elapsed, timeout};
use tracing;

use argus_protocol::llm::{
    ChatMessage, CompletionRequest, CompletionResponse, FinishReason, LlmProvider, LlmStreamEvent,
    ToolCall, ToolDefinition,
};
use argus_protocol::tool::NamedTool;
use argus_protocol::{
    AgentRecord, HookAction, HookEvent, HookHandler, ThreadEvent, ThreadMailbox, TokenUsage,
    ToolExecutionContext, ToolHookContext, ids::ThreadId, sanitize_tool_output,
};

use super::tool_context::{clear_current_agent_id, set_current_agent_id};
use super::{TurnConfig, TurnError, TurnOutput, TurnStreamEvent};

/// Cancellation primitive used to stop an active turn.
///
/// This token is cloneable so the runtime can hold a handle to cancel the active
/// turn while the turn itself periodically checks for cancellation.
#[derive(Clone, Debug)]
pub struct TurnCancellation {
    tx: watch::Sender<bool>,
    rx: watch::Receiver<bool>,
}

impl TurnCancellation {
    #[must_use]
    pub fn new() -> Self {
        let (tx, rx) = watch::channel(false);
        Self { tx, rx }
    }

    pub fn cancel(&self) {
        let _ = self.tx.send(true);
    }

    #[must_use]
    pub fn is_cancelled(&self) -> bool {
        *self.rx.borrow()
    }

    #[must_use]
    pub fn subscribe(&self) -> watch::Receiver<bool> {
        self.rx.clone()
    }

    pub async fn cancelled(&self) {
        if self.is_cancelled() {
            return;
        }

        let mut rx = self.subscribe();
        loop {
            if rx.changed().await.is_err() {
                return;
            }
            if *rx.borrow() {
                return;
            }
        }
    }
}

impl Default for TurnCancellation {
    fn default() -> Self {
        Self::new()
    }
}

/// Turn identifier generator (simple counter for now).
fn generate_turn_id(thread_id: &str, turn_number: u32) -> String {
    format!("{}-turn-{}", thread_id, turn_number)
}

fn dummy_control_tx() -> mpsc::UnboundedSender<argus_protocol::ThreadControlEvent> {
    let (tx, _rx) = mpsc::unbounded_channel();
    tx
}

fn default_mailbox() -> Arc<Mutex<ThreadMailbox>> {
    Arc::new(Mutex::new(ThreadMailbox::default()))
}

/// Result of processing an LLM response's finish_reason.
enum NextAction {
    /// Turn is complete, return the output.
    Return(TurnOutput),
    /// Continue with tool execution.
    ContinueWithTools {
        tool_calls: Vec<ToolCall>,
        content: Option<String>,
    },
    /// Context length exceeded.
    LengthExceeded,
}

enum StreamingCallOutcome {
    Completed(CompletionResponse),
    Failed {
        partial_response: CompletionResponse,
        error: argus_protocol::llm::LlmError,
    },
}

/// Result of a tool execution.
struct ToolExecutionResult {
    tool_call_id: String,
    name: String,
    content: String,
}

/// Accumulates streaming events into a complete response.
struct StreamingAccumulator {
    content: String,
    reasoning_content: String,
    tool_calls: Vec<(Option<String>, Option<String>, String)>,
    input_tokens: u32,
    output_tokens: u32,
    finish_reason: FinishReason,
}

impl StreamingAccumulator {
    fn new() -> Self {
        Self {
            content: String::new(),
            reasoning_content: String::new(),
            tool_calls: Vec::new(),
            input_tokens: 0,
            output_tokens: 0,
            finish_reason: FinishReason::Stop,
        }
    }

    fn process(&mut self, event: LlmStreamEvent) {
        match event {
            LlmStreamEvent::ReasoningDelta { delta } => {
                self.reasoning_content.push_str(&delta);
            }
            LlmStreamEvent::ContentDelta { delta } => {
                self.content.push_str(&delta);
            }
            LlmStreamEvent::ToolCallDelta(tc) => {
                // Ensure we have enough slots
                while self.tool_calls.len() <= tc.index {
                    self.tool_calls.push((None, None, String::new()));
                }
                if let Some(id) = tc.id {
                    self.tool_calls[tc.index].0 = Some(id);
                }
                if let Some(name) = tc.name {
                    self.tool_calls[tc.index].1 = Some(name);
                }
                if let Some(args_delta) = tc.arguments_delta {
                    self.tool_calls[tc.index].2.push_str(&args_delta);
                }
            }
            LlmStreamEvent::Usage {
                input_tokens,
                output_tokens,
            } => {
                self.input_tokens = input_tokens;
                self.output_tokens = output_tokens;
            }
            LlmStreamEvent::Finished { finish_reason } => {
                self.finish_reason = finish_reason;
            }
            LlmStreamEvent::RetryAttempt { .. } => {
                // Retry events are informational and forwarded to subscribers,
                // but don't affect the accumulated response state
            }
        }
    }

    fn into_response(self) -> CompletionResponse {
        // Convert accumulated tool calls to ToolCall structs
        let tool_calls: Vec<ToolCall> = self
            .tool_calls
            .into_iter()
            .filter_map(|(id, name, args)| {
                Some(ToolCall {
                    id: id?,
                    name: name?,
                    arguments: serde_json::from_str(&args).unwrap_or(serde_json::Value::Null),
                })
            })
            .collect();

        CompletionResponse {
            content: if self.content.is_empty() {
                None
            } else {
                Some(self.content)
            },
            reasoning_content: if self.reasoning_content.is_empty() {
                None
            } else {
                Some(self.reasoning_content)
            },
            tool_calls,
            input_tokens: self.input_tokens,
            output_tokens: self.output_tokens,
            finish_reason: self.finish_reason,
            cache_read_input_tokens: 0,
            cache_creation_input_tokens: 0,
        }
    }
}

/// A Turn represents a single execution cycle in a conversation.
///
/// The Turn owns its resources (tools and hooks) directly and is responsible
/// only for execution logic. Construction is handled by `TurnBuilder` or the Thread layer.
///
/// # Lifecycle
///
/// 1. **Construction**: Built via `TurnBuilder` with all required fields
/// 2. **Execution**: Call `.execute()` to run the turn (consumes self)
/// 3. **Completion**: Returns `TurnOutput` with appended messages and token usage
///
/// # Example
///
/// ```ignore
/// use argus_agent::{Turn, TurnBuilder};
/// use argus_protocol::llm::ChatMessage;
///
/// let turn = TurnBuilder::new()
///     .turn_number(1)
///     .thread_id("thread-123".to_string())
///     .messages(vec![ChatMessage::user("Hello!")])
///     .provider(provider)
///     .tools(vec![Arc::new(my_tool)])
///     .hooks(vec![Arc::new(my_hook)])
///     .config(TurnConfig::default())
///     .stream_tx(stream_tx)
///     .thread_event_tx(thread_event_tx)
///     .build()?;
///
/// let output = turn.execute().await?;
/// ```
#[derive(Builder)]
#[builder(pattern = "owned", build_fn(error = "TurnError"), name = "TurnBuilder")]
pub struct Turn {
    /// Turn identifier (auto-generated from thread_id and turn_number).
    #[builder(
        default = "generate_turn_id(self.thread_id.as_ref().unwrap_or(&\"unknown\".to_string()), *self.turn_number.as_ref().unwrap_or(&0))"
    )]
    pub id: String,

    /// Turn number (sequence in the thread).
    #[builder(setter(custom))]
    turn_number: u32,

    /// Thread identifier.
    #[builder(setter(custom))]
    thread_id: String,

    /// Stable routing thread used for control-plane callbacks and nested jobs.
    #[builder(default = "ThreadId::new()", setter(custom))]
    originating_thread_id: ThreadId,

    /// Session identifier (for callback).
    #[builder(default, setter(strip_option))]
    session_id: Option<argus_protocol::SessionId>,

    /// Shared base message history for this turn.
    #[builder(setter(custom), default = "Arc::new(Vec::new())")]
    messages: Arc<Vec<ChatMessage>>,

    /// Messages appended during this turn.
    #[builder(default)]
    pending_messages: Vec<ChatMessage>,

    /// LLM provider for completion requests.
    provider: Arc<dyn LlmProvider>,

    /// Tools available for this turn (direct ownership, no ToolManager needed).
    #[builder(default)]
    tools: Vec<Arc<dyn NamedTool>>,

    /// Hooks for lifecycle events (direct ownership, no HookRegistry needed).
    #[builder(default)]
    hooks: Vec<Arc<dyn HookHandler>>,

    /// Turn execution configuration.
    #[builder(default)]
    config: TurnConfig,

    /// Agent record (shared from Thread).
    agent_record: Arc<AgentRecord>,

    /// Internal stream event sender.
    stream_tx: broadcast::Sender<TurnStreamEvent>,

    /// Thread event sender for broadcasting to subscribers.
    thread_event_tx: broadcast::Sender<ThreadEvent>,

    /// Control sender used by nested tool executions.
    #[builder(default = "dummy_control_tx()")]
    control_tx: mpsc::UnboundedSender<argus_protocol::ThreadControlEvent>,

    /// Shared thread mailbox consulted before each loop iteration.
    ///
    /// Note: this mailbox is a legacy compatibility path for in-turn injected control
    /// inputs (e.g. interrupts). The primary production queue model for user messages
    /// and job results is the thread runtime actor's FIFO inbox.
    #[builder(default = "default_mailbox()")]
    mailbox: Arc<Mutex<ThreadMailbox>>,

    /// Cancellation primitive used to stop this turn.
    #[builder(default)]
    cancellation: TurnCancellation,

    /// Event forwarder task handle (cleaned up on drop).
    #[builder(default)]
    _forwarder_handle: Option<tokio::task::JoinHandle<()>>,

}

impl TurnBuilder {
    /// Set the base message history for this turn.
    pub fn messages(mut self, value: Vec<ChatMessage>) -> Self {
        self.messages = Some(Arc::new(value));
        self
    }

    /// Share an existing history buffer with this turn.
    pub fn shared_messages(mut self, value: Arc<Vec<ChatMessage>>) -> Self {
        self.messages = Some(value);
        self
    }

    /// Set turn number.
    pub fn turn_number(mut self, value: u32) -> Self {
        self.turn_number = Some(value);
        self
    }

    /// Set thread ID.
    pub fn thread_id(mut self, value: String) -> Self {
        self.thread_id = Some(value);
        self
    }

    /// Set the stable originating thread route for control-plane callbacks.
    pub fn originating_thread_id(mut self, value: ThreadId) -> Self {
        self.originating_thread_id = Some(value);
        self
    }
}

impl std::fmt::Debug for Turn {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Turn")
            .field("id", &self.id)
            .field("turn_number", &self.turn_number)
            .field("thread_id", &self.thread_id)
            .field("messages", &self.messages.len())
            .field("provider", &self.provider.model_name())
            .field("tools", &self.tools.len())
            .field("hooks", &self.hooks.len())
            .field("config", &self.config)
            .finish()
    }
}

impl Turn {
    fn materialize_messages(&self, pending_messages: &[ChatMessage]) -> Vec<ChatMessage> {
        let mut messages =
            Vec::with_capacity(self.messages.len().saturating_add(pending_messages.len()));
        messages.extend(self.messages.iter().cloned());
        messages.extend(pending_messages.iter().cloned());
        messages
    }

    /// Execute the turn and return the output.
    ///
    /// This method:
    /// 1. Spawns the event forwarder task
    /// 2. Executes the main LLM -> Tool -> LLM loop
    /// 3. Sends TurnCompleted/TurnFailed event
    /// 4. Sends Idle event
    /// 5. Returns TurnOutput with updated messages and token usage
    ///
    /// # Errors
    ///
    /// Returns `TurnError` for:
    /// - LLM failures
    /// - Tool execution failures
    /// - Hook blocks
    /// - Max iterations exceeded
    pub async fn execute(mut self) -> Result<TurnOutput, TurnError> {
        // Spawn event forwarder — clone stream_tx so it lives in the forwarder task.
        // This prevents the channel from closing when the Turn is dropped.
        self._forwarder_handle = Some(Self::spawn_event_forwarder(
            self.stream_tx.clone(),
            self.thread_event_tx.clone(),
            self.thread_id.clone(),
            self.turn_number,
        ));

        tracing::info!(
            thread_id = %self.thread_id,
            turn_number = %self.turn_number,
            tool_count = %self.tools.len(),
            hook_count = %self.hooks.len(),
            "Turn execution started"
        );

        let result = self.execute_loop().await;

        tracing::info!(
            thread_id = %self.thread_id,
            turn_number = %self.turn_number,
            result = ?result.as_ref().map(|_| "ok"),
            "Turn execution completed"
        );

        let cancelled = matches!(result, Err(TurnError::Cancelled));

        // Invoke on_turn_complete callback if configured
        if !cancelled
            && let (Some(callback), Some(session_id)) =
                (&self.config.on_turn_complete, &self.session_id)
        {
            callback(*session_id, self.turn_number);
        }

        // Send completion event
        match &result {
            Ok(output) => {
                if let Err(e) = self.thread_event_tx.send(ThreadEvent::TurnCompleted {
                    thread_id: self.thread_id.clone(),
                    turn_number: self.turn_number,
                    token_usage: output.token_usage.clone(),
                }) {
                    tracing::warn!(
                        thread_id = %self.thread_id,
                        error = %e,
                        "Failed to send TurnCompleted event"
                    );
                }
            }
            Err(TurnError::Cancelled) => {
                // Cancellation is an expected control-path outcome. Do not emit TurnFailed;
                // callers will still observe ThreadEvent::Idle.
            }
            Err(error) => {
                if let Err(e) = self.thread_event_tx.send(ThreadEvent::TurnFailed {
                    thread_id: self.thread_id.clone(),
                    turn_number: self.turn_number,
                    error: error.to_string(),
                }) {
                    tracing::warn!(
                        thread_id = %self.thread_id,
                        error = %e,
                        "Failed to send TurnFailed event"
                    );
                }
            }
        }

        // Send Idle event
        if let Err(e) = self.thread_event_tx.send(ThreadEvent::Idle {
            thread_id: self.thread_id.clone(),
        }) {
            tracing::warn!(
                thread_id = %self.thread_id,
                error = %e,
                "Failed to send Idle event"
            );
        }

        result
    }

    /// Internal method: spawn event forwarder task.
    ///
    /// Forwards TurnStreamEvent to ThreadEvent for external subscribers.
    /// Returns the JoinHandle so the caller can store it.
    fn spawn_event_forwarder(
        stream_tx: broadcast::Sender<TurnStreamEvent>,
        thread_event_tx: broadcast::Sender<ThreadEvent>,
        thread_id: String,
        turn_number: u32,
    ) -> tokio::task::JoinHandle<()> {
        let mut stream_rx = stream_tx.subscribe();

        tokio::spawn(async move {
            tracing::debug!(
                thread_id = %thread_id,
                turn_number = %turn_number,
                "Event forwarder started"
            );
            while let Ok(event) = stream_rx.recv().await {
                match event {
                    TurnStreamEvent::LlmEvent(llm_event) => {
                        if let Err(e) = thread_event_tx.send(ThreadEvent::Processing {
                            thread_id: thread_id.clone(),
                            turn_number,
                            event: llm_event,
                        }) {
                            tracing::warn!(
                                thread_id = %thread_id,
                                turn_number = %turn_number,
                                error = %e,
                                "Failed to forward LlmEvent to thread_event_tx"
                            );
                        }
                    }
                    TurnStreamEvent::ToolStarted {
                        tool_call_id,
                        tool_name,
                        arguments,
                    } => {
                        if let Err(e) = thread_event_tx.send(ThreadEvent::ToolStarted {
                            thread_id: thread_id.clone(),
                            turn_number,
                            tool_call_id,
                            tool_name,
                            arguments,
                        }) {
                            tracing::warn!(
                                thread_id = %thread_id,
                                turn_number = %turn_number,
                                error = %e,
                                "Failed to forward ToolStarted to thread_event_tx"
                            );
                        }
                    }
                    TurnStreamEvent::ToolCompleted {
                        tool_call_id,
                        tool_name,
                        result,
                    } => {
                        if let Err(e) = thread_event_tx.send(ThreadEvent::ToolCompleted {
                            thread_id: thread_id.clone(),
                            turn_number,
                            tool_call_id,
                            tool_name,
                            result,
                        }) {
                            tracing::warn!(
                                thread_id = %thread_id,
                                turn_number = %turn_number,
                                error = %e,
                                "Failed to forward ToolCompleted to thread_event_tx"
                            );
                        }
                    }
                }
            }
            tracing::warn!(
                thread_id = %thread_id,
                turn_number = %turn_number,
                "Event forwarder stopped (stream channel closed)"
            );
        })
    }

    /// Internal method: trigger hooks and return the action.
    async fn fire_hooks(&self, ctx: &ToolHookContext) -> Result<HookAction, TurnError> {
        for hook in &self.hooks {
            let action = hook.on_tool_event(ctx).await;

            if let HookAction::Block(reason) = action {
                return Ok(HookAction::Block(reason));
            }

            if !matches!(action, HookAction::Continue) {
                return Ok(action);
            }
        }

        Ok(HookAction::Continue)
    }

    /// Internal method: execute the main LLM -> Tool -> LLM loop.
    ///
    /// This is where the core execution logic lives.
    async fn execute_loop(
        &mut self,
    ) -> Result<TurnOutput, TurnError> {
        let mut pending_messages = std::mem::take(&mut self.pending_messages);
        let max_iterations = self.config.max_iterations.unwrap_or(50);
        let tool_timeout_secs = self.config.tool_timeout_secs.unwrap_or(120);
        let mut token_usage = TokenUsage::default();

        let max_tool_calls = self.config.max_tool_calls;

        for iteration in 0..max_iterations {
            if self.cancellation.is_cancelled() {
                return Err(TurnError::Cancelled);
            }

            let pending_inputs = {
                let mut mailbox = self.mailbox.lock().await;
                mailbox.drain_for_turn()
            };

            for input in pending_inputs {
                let content = input.into_message_text();
                tracing::debug!("injecting control input into turn: {}", content);
                pending_messages.push(ChatMessage::user(&content));
            }

            let mut request_messages = self.materialize_messages(&pending_messages);
            if let Some(max) = max_tool_calls
                && !self.tools.is_empty()
            {
                let system_content = format!(
                    "IMPORTANT: You can only call at most {} tool(s) per response. \
                    If you need to call multiple tools, please proceed step by step - \
                    call tools one at a time and wait for the results before calling the next tool.",
                    max
                );
                request_messages.insert(0, ChatMessage::system(system_content));
            }

            tracing::debug!(
                thread_id = %self.thread_id,
                turn_number = %self.turn_number,
                iteration = %iteration,
                max_iterations = %max_iterations,
                message_count = %request_messages.len(),
                "Turn iteration started"
            );

            // Prepare tools from self.tools
            let tools: Vec<ToolDefinition> = self.tools.iter().map(|t| t.definition()).collect();

            // Build the request with current messages and tools
            let mut request =
                CompletionRequest::new(request_messages.clone()).with_tools(tools.clone());
            if let Some(max_tokens) = self.agent_record.max_tokens {
                request.max_tokens = Some(max_tokens);
            }
            if let Some(temperature) = self.agent_record.temperature {
                request.temperature = Some(temperature);
            }
            if let Some(thinking_config) = &self.agent_record.thinking_config {
                request.thinking = Some(thinking_config.clone());
            }

            tracing::debug!(
                thread_id = %self.thread_id,
                turn_number = %self.turn_number,
                iteration = %iteration,
                tool_count = %tools.len(),
                message_count = %request_messages.len(),
                "Calling LLM"
            );
            let response = match self.call_llm_streaming(request).await {
                Ok(StreamingCallOutcome::Completed(response)) => response,
                Ok(StreamingCallOutcome::Failed {
                    partial_response,
                    error,
                }) => {
                    let _ = partial_response;
                    return Err(TurnError::LlmFailed(error));
                }
                Err(error) => return Err(error),
            };
            tracing::debug!(
                thread_id = %self.thread_id,
                turn_number = %self.turn_number,
                iteration = %iteration,
                "LLM call completed"
            );

            // Process response
            let next_action = match self
                .process_finish_reason(response, &mut pending_messages, &mut token_usage)
            {
                Ok(next_action) => next_action,
                Err(error) => return Err(error),
            };
            match next_action {
                NextAction::Return(output) => {
                    // Fire TurnEnd hook
                    let ctx = ToolHookContext {
                        event: HookEvent::TurnEnd,
                        tool_name: String::new(),
                        tool_call_id: String::new(),
                        tool_input: serde_json::Value::Null,
                        tool_result: None,
                        error: None,
                        tool_manager: None,
                        thread_event_sender: Some(self.thread_event_tx.clone()),
                        thread_id: Some(self.thread_id.clone()),
                        turn_number: Some(self.turn_number),
                    };
                    let turn_end_action = self.fire_hooks(&ctx).await;

                    let mut output = output;
                    let continue_message = match turn_end_action {
                        Ok(HookAction::ContinueWithMessage(message)) => Some(message),
                        Ok(HookAction::Continue) => None,
                        Ok(HookAction::Block(reason)) => {
                            tracing::warn!(
                                reason = %reason,
                                "TurnEnd hook returned Block (ignored)"
                            );
                            None
                        }
                        Err(error) => {
                            tracing::warn!(
                                error = %error,
                                "TurnEnd hook failed (ignored)"
                            );
                            None
                        }
                    };

                    if let Some(message) = continue_message {
                        pending_messages = std::mem::take(&mut output.appended_messages);
                        pending_messages.push(ChatMessage::user(&message));

                        tracing::debug!(
                            thread_id = %self.thread_id,
                            turn_number = %self.turn_number,
                            iteration = %iteration,
                            "TurnEnd hook requested continuation with injected user message"
                        );
                        continue;
                    }

                    return Ok(output);
                }
                NextAction::ContinueWithTools {
                    tool_calls,
                    content,
                } => {
                    tracing::debug!(
                        thread_id = %self.thread_id,
                        turn_number = %self.turn_number,
                        iteration = %iteration,
                        tool_count = %tool_calls.len(),
                        content_preview = %content.as_ref().map(|c| c.chars().take(100).collect::<String>()).unwrap_or_default(),
                        "Tool calls detected, executing tools"
                    );

                    // Execute tools in parallel
                    let tool_results = tokio::select! {
                        _ = self.cancellation.cancelled() => {
                            return Err(TurnError::Cancelled);
                        }
                        tool_results = self.execute_tools_parallel(tool_calls, tool_timeout_secs) => tool_results,
                    };

                    tracing::debug!(
                        thread_id = %self.thread_id,
                        turn_number = %self.turn_number,
                        iteration = %iteration,
                        result_count = %tool_results.len(),
                        "Tools executed, adding results to message history"
                    );

                    // Add tool result messages to history
                    for result in tool_results {
                        let (sanitized_content, warning) =
                            sanitize_tool_output(&result.content, &self.config.safety_config);

                        if let Some(w) = &warning {
                            tracing::warn!(
                                thread_id = %self.thread_id,
                                turn_number = %self.turn_number,
                                tool_call_id = %result.tool_call_id,
                                tool_name = %result.name,
                                pattern = %w.pattern,
                                original_len = w.original_len,
                                truncated_len = w.truncated_len,
                                "Tool output was truncated"
                            );
                        }

                        let result_len = sanitized_content.len();
                        let preview = sanitized_content.chars().take(200).collect::<String>();
                        tracing::info!(
                            thread_id = %self.thread_id,
                            turn_number = %self.turn_number,
                            tool_call_id = %result.tool_call_id,
                            tool_name = %result.name,
                            result_len,
                            result_preview = %preview,
                            "Tool result added to history"
                        );
                        pending_messages.push(ChatMessage::tool_result(
                            result.tool_call_id,
                            result.name,
                            sanitized_content,
                        ));
                    }

                    // Continue the loop with updated messages
                }
                NextAction::LengthExceeded => {
                    return Err(TurnError::ContextLengthExceeded(
                        (token_usage.input_tokens + token_usage.output_tokens) as usize,
                    ));
                }
            }
        }

        // Max iterations reached
        Err(TurnError::MaxIterationsReached(max_iterations))
    }

    /// Calls the LLM in streaming mode, accumulating the response.
    ///
    /// Falls back to non-streaming if the provider doesn't support streaming.
    async fn call_llm_streaming(
        &self,
        request: CompletionRequest,
    ) -> Result<StreamingCallOutcome, TurnError> {
        if self.cancellation.is_cancelled() {
            return Err(TurnError::Cancelled);
        }

        match self.provider.stream_complete(request.clone()).await {
            Ok(mut stream) => {
                tracing::debug!(
                    thread_id = %self.thread_id,
                    turn_number = %self.turn_number,
                    "LLM stream started"
                );
                let mut cancel_rx = self.cancellation.subscribe();
                let mut accumulator = StreamingAccumulator::new();
                loop {
                    tokio::select! {
                        change = cancel_rx.changed() => {
                            if change.is_ok() && *cancel_rx.borrow() {
                                return Err(TurnError::Cancelled);
                            }
                        }
                        event_result = stream.next() => {
                            let Some(event_result) = event_result else {
                                break;
                            };

                            let event = match event_result {
                                Ok(event) => event,
                                Err(error) => {
                                    return Ok(StreamingCallOutcome::Failed {
                                        partial_response: accumulator.into_response(),
                                        error,
                                    });
                                }
                            };
                            // Forward to stream_tx
                            let _ = self
                                .stream_tx
                                .send(TurnStreamEvent::LlmEvent(event.clone()));
                            accumulator.process(event);
                        }
                    }
                }
                let response = accumulator.into_response();
                tracing::debug!(
                    thread_id = %self.thread_id,
                    turn_number = %self.turn_number,
                    finish_reason = ?response.finish_reason,
                    tool_call_count = %response.tool_calls.len(),
                    "LLM stream completed"
                );
                Ok(StreamingCallOutcome::Completed(response))
            }
            Err(argus_protocol::llm::LlmError::UnsupportedCapability { .. }) => {
                // Fallback to non-streaming
                tracing::debug!("Provider doesn't support streaming, using non-streaming fallback");
                tokio::select! {
                    _ = self.cancellation.cancelled() => Err(TurnError::Cancelled),
                    result = self.provider.complete(request) => result.map(StreamingCallOutcome::Completed).map_err(TurnError::LlmFailed),
                }
            }
            Err(e) => Err(TurnError::LlmFailed(e)),
        }
    }

    /// Processes the LLM response and determines the next action.
    fn process_finish_reason(
        &self,
        response: CompletionResponse,
        pending_messages: &mut Vec<ChatMessage>,
        token_usage: &mut TokenUsage,
    ) -> Result<NextAction, TurnError> {
        let CompletionResponse {
            content,
            reasoning_content,
            tool_calls: response_tool_calls,
            input_tokens,
            output_tokens,
            finish_reason,
            ..
        } = response;

        // Track token usage
        token_usage.input_tokens += input_tokens;
        token_usage.output_tokens += output_tokens;
        token_usage.total_tokens += input_tokens + output_tokens;

        match finish_reason {
            FinishReason::Stop => {
                if content.as_deref().is_some_and(|value| !value.is_empty())
                    || reasoning_content
                        .as_deref()
                        .is_some_and(|value| !value.is_empty())
                {
                    pending_messages.push(ChatMessage::assistant_with_reasoning(
                        content.unwrap_or_default(),
                        reasoning_content,
                    ));
                }

                Ok(NextAction::Return(TurnOutput {
                    appended_messages: std::mem::take(pending_messages),
                    token_usage: token_usage.clone(),
                }))
            }
            FinishReason::ToolUse => {
                // Limit tool calls based on max_tool_calls config
                let tool_calls: Vec<ToolCall> = match self.config.max_tool_calls {
                    Some(max) if response_tool_calls.len() > max as usize => {
                        tracing::debug!(
                            requested = response_tool_calls.len(),
                            max_allowed = max,
                            "Limiting tool calls per iteration"
                        );
                        response_tool_calls.into_iter().take(max as usize).collect()
                    }
                    _ => response_tool_calls,
                };

                // Add assistant message with tool_calls to history
                let assistant_msg = ChatMessage::assistant_with_tool_calls_and_reasoning(
                    content.clone(),
                    tool_calls.clone(),
                    reasoning_content,
                );
                pending_messages.push(assistant_msg);

                Ok(NextAction::ContinueWithTools {
                    tool_calls,
                    content,
                })
            }
            FinishReason::Length => Ok(NextAction::LengthExceeded),
            FinishReason::ContentFilter | FinishReason::Unknown => {
                // If there are actual tool calls, treat as ToolUse (some providers
                // return non-standard finish_reason values when tool calls are present)
                if !response_tool_calls.is_empty() {
                    let tool_calls: Vec<ToolCall> = match self.config.max_tool_calls {
                        Some(max) if response_tool_calls.len() > max as usize => {
                            tracing::debug!(
                                requested = response_tool_calls.len(),
                                max_allowed = max,
                                "Limiting tool calls per iteration"
                            );
                            response_tool_calls.into_iter().take(max as usize).collect()
                        }
                        _ => response_tool_calls,
                    };

                    let assistant_msg = ChatMessage::assistant_with_tool_calls_and_reasoning(
                        content.clone(),
                        tool_calls.clone(),
                        reasoning_content,
                    );
                    pending_messages.push(assistant_msg);

                    Ok(NextAction::ContinueWithTools {
                        tool_calls,
                        content,
                    })
                } else if content.as_deref().is_some_and(|value| !value.is_empty())
                    || reasoning_content
                        .as_deref()
                        .is_some_and(|value| !value.is_empty())
                {
                    pending_messages.push(ChatMessage::assistant_with_reasoning(
                        content.unwrap_or_default(),
                        reasoning_content,
                    ));

                    Ok(NextAction::Return(TurnOutput {
                        appended_messages: std::mem::take(pending_messages),
                        token_usage: token_usage.clone(),
                    }))
                } else {
                    Ok(NextAction::Return(TurnOutput {
                        appended_messages: std::mem::take(pending_messages),
                        token_usage: token_usage.clone(),
                    }))
                }
            }
        }
    }

    /// Executes multiple tool calls in parallel.
    async fn execute_tools_parallel(
        &self,
        tool_calls: Vec<ToolCall>,
        tool_timeout_secs: u64,
    ) -> Vec<ToolExecutionResult> {
        let futures: Vec<_> = tool_calls
            .into_iter()
            .map(|tool_call| self.execute_single_tool(tool_call, tool_timeout_secs))
            .collect();

        join_all(futures).await
    }

    /// Executes a single tool call with hooks and timeout.
    async fn execute_single_tool(
        &self,
        tool_call: ToolCall,
        tool_timeout_secs: u64,
    ) -> ToolExecutionResult {
        let tool_call_id = tool_call.id.clone();
        let tool_name = tool_call.name.clone();
        let tool_input = tool_call.arguments.clone();

        // Find the tool in self.tools
        let tool = self.tools.iter().find(|t| t.name() == tool_name).cloned();

        // Fire BeforeToolCall hook
        let ctx = ToolHookContext {
            event: HookEvent::BeforeToolCall,
            tool_name: tool_name.clone(),
            tool_call_id: tool_call_id.clone(),
            tool_input: tool_input.clone(),
            tool_result: None,
            error: None,
            tool_manager: tool.clone(),
            thread_event_sender: Some(self.thread_event_tx.clone()),
            thread_id: Some(self.thread_id.clone()),
            turn_number: Some(self.turn_number),
        };

        if let Ok(HookAction::Block(ref reason)) = self.fire_hooks(&ctx).await
        {
            // Hook blocked the tool call
            let content = format!("Tool call blocked: {}", reason);

            // Fire AfterToolCall hook with error
            let after_ctx = ToolHookContext {
                event: HookEvent::AfterToolCall,
                tool_name: tool_name.clone(),
                tool_call_id: tool_call_id.clone(),
                tool_input,
                tool_result: None,
                error: Some(reason.clone()),
                tool_manager: None,
                thread_event_sender: Some(self.thread_event_tx.clone()),
                thread_id: Some(self.thread_id.clone()),
                turn_number: Some(self.turn_number),
            };
            let _ = self.fire_hooks(&after_ctx).await;

            return ToolExecutionResult {
                tool_call_id,
                name: tool_name,
                content,
            };
        }

        // Send ToolStarted events
        if let Err(e) = self.thread_event_tx.send(ThreadEvent::ToolStarted {
            thread_id: self.thread_id.clone(),
            turn_number: self.turn_number,
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            arguments: tool_input.clone(),
        }) {
            tracing::warn!(
                thread_id = %self.thread_id,
                turn_number = %self.turn_number,
                tool_name = %tool_name,
                error = %e,
                "Failed to send ToolStarted event"
            );
        }
        let _ = self.stream_tx.send(TurnStreamEvent::ToolStarted {
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            arguments: tool_input.clone(),
        });

        // Execute the tool with timeout
        let timeout_duration = std::time::Duration::from_secs(tool_timeout_secs);
        set_current_agent_id(self.agent_record.id);
        let start_time = std::time::Instant::now();
        let execute_result = {
            let execute_future = async {
                if let Some(tool) = tool {
                    tracing::debug!(
                        thread_id = %self.thread_id,
                        turn_number = %self.turn_number,
                        tool_call_id = %tool_call_id,
                        tool_name = %tool_name,
                        "Executing tool"
                    );
                    let ctx = Arc::new(ToolExecutionContext {
                        thread_id: self.originating_thread_id,
                        agent_id: Some(self.agent_record.id),
                        pipe_tx: self.thread_event_tx.clone(),
                        control_tx: self.control_tx.clone(),
                    });
                    tool.execute(tool_input.clone(), ctx).await
                } else {
                    tracing::error!(
                        thread_id = %self.thread_id,
                        turn_number = %self.turn_number,
                        tool_call_id = %tool_call_id,
                        tool_name = %tool_name,
                        available_tools = ?self.tools.iter().map(|t| t.name()).collect::<Vec<_>>(),
                        "Tool not found in registry"
                    );
                    Err(argus_protocol::tool::ToolError::NotFound {
                        id: tool_name.clone(),
                    })
                }
            };
            timeout(timeout_duration, execute_future).await
        };
        clear_current_agent_id();

        let result = match execute_result {
            Ok(Ok(value)) => {
                tracing::info!(
                    thread_id = %self.thread_id,
                    turn_number = %self.turn_number,
                    tool_call_id = %tool_call_id,
                    tool_name = %tool_name,
                    result_preview = %value.to_string().chars().take(200).collect::<String>(),
                    "Tool executed successfully"
                );
                Ok(value)
            }
            Ok(Err(e)) => {
                tracing::warn!(
                    thread_id = %self.thread_id,
                    turn_number = %self.turn_number,
                    tool_call_id = %tool_call_id,
                    tool_name = %tool_name,
                    error = %e,
                    "Tool execution returned error"
                );
                Err(e.to_string())
            }
            Err(Elapsed { .. }) => {
                tracing::error!(
                    thread_id = %self.thread_id,
                    turn_number = %self.turn_number,
                    tool_call_id = %tool_call_id,
                    tool_name = %tool_name,
                    timeout_secs = %tool_timeout_secs,
                    "Tool execution timed out"
                );
                Err(format!(
                    "Tool execution timed out after {}s",
                    tool_timeout_secs
                ))
            }
        };

        // Send ToolCompleted events
        let event_result = match &result {
            Ok(value) => Ok(value.clone()),
            Err(e) => Err(e.clone()),
        };
        if let Err(e) = self.thread_event_tx.send(ThreadEvent::ToolCompleted {
            thread_id: self.thread_id.clone(),
            turn_number: self.turn_number,
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            result: event_result.clone(),
        }) {
            tracing::warn!(
                thread_id = %self.thread_id,
                turn_number = %self.turn_number,
                tool_name = %tool_name,
                error = %e,
                "Failed to send ToolCompleted event"
            );
        }
        let _ = self.stream_tx.send(TurnStreamEvent::ToolCompleted {
            tool_call_id: tool_call_id.clone(),
            tool_name: tool_name.clone(),
            result: event_result,
        });

        // Fire AfterToolCall hook
        let (tool_result, error) = match &result {
            Ok(value) => (Some(value.clone()), None),
            Err(e) => (None, Some(e.clone())),
        };
        let ctx = ToolHookContext {
            event: HookEvent::AfterToolCall,
            tool_name: tool_name.clone(),
            tool_call_id: tool_call_id.clone(),
            tool_input,
            tool_result,
            error,
            tool_manager: None,
            thread_event_sender: Some(self.thread_event_tx.clone()),
            thread_id: Some(self.thread_id.clone()),
            turn_number: Some(self.turn_number),
        };
        let _ = self.fire_hooks(&ctx).await;

        // Convert result to string content.
        let _duration_ms = start_time.elapsed().as_millis() as u64;
        let content = match &result {
            Ok(value) => serde_json::to_string(value).unwrap_or_else(|e| {
                format!("{{\"error\": \"Failed to serialize result: {}\"}}", e)
            }),
            Err(e) => format!("{{\"error\": \"{}\"}}", e),
        };

        ToolExecutionResult {
            tool_call_id,
            name: tool_name,
            content,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Arc, Mutex};

    use argus_protocol::llm::{CompletionRequest, CompletionResponse, LlmError};
    use argus_protocol::{AgentId, AgentType, ProviderId};
    use async_trait::async_trait;
    use rust_decimal::Decimal;
    use tokio::sync::broadcast;

    #[test]
    fn test_generate_turn_id() {
        let id = generate_turn_id("thread-123", 5);
        assert_eq!(id, "thread-123-turn-5");
    }

    #[test]
    fn test_turn_builder_requires_turn_number_and_thread_id() {
        // This test verifies the builder API
        // Actual builder validation will be done in integration tests
    }

    #[test]
    fn test_turn_debug_format() {
        // Create channels for testing
        let (stream_tx, _): (broadcast::Sender<TurnStreamEvent>, _) = broadcast::channel(256);
        let (thread_event_tx, _): (broadcast::Sender<ThreadEvent>, _) = broadcast::channel(256);

        // Note: We can't easily test this without a mock provider
        // This is just a placeholder test to verify channel creation works
        let _ = (stream_tx, thread_event_tx);
    }

    #[derive(Debug)]
    struct SequencedProvider {
        responses: Mutex<Vec<CompletionResponse>>,
    }

    impl SequencedProvider {
        fn new(responses: Vec<CompletionResponse>) -> Self {
            Self {
                responses: Mutex::new(responses),
            }
        }
    }

    #[async_trait]
    impl LlmProvider for SequencedProvider {
        fn model_name(&self) -> &str {
            "sequenced"
        }

        fn cost_per_token(&self) -> (Decimal, Decimal) {
            (Decimal::ZERO, Decimal::ZERO)
        }

        async fn complete(
            &self,
            _request: CompletionRequest,
        ) -> Result<CompletionResponse, LlmError> {
            let mut responses = self.responses.lock().unwrap();
            if responses.is_empty() {
                return Ok(CompletionResponse {
                    content: Some("done".to_string()),
                    reasoning_content: None,
                    tool_calls: Vec::new(),
                    input_tokens: 1,
                    output_tokens: 1,
                    finish_reason: FinishReason::Stop,
                    cache_read_input_tokens: 0,
                    cache_creation_input_tokens: 0,
                });
            }
            Ok(responses.remove(0))
        }
    }

    struct ContinueOnceTurnEndHook {
        used: Mutex<bool>,
    }

    impl ContinueOnceTurnEndHook {
        fn new() -> Self {
            Self {
                used: Mutex::new(false),
            }
        }
    }

    #[async_trait]
    impl HookHandler for ContinueOnceTurnEndHook {
        async fn on_tool_event(&self, ctx: &ToolHookContext) -> HookAction {
            if ctx.event == HookEvent::TurnEnd {
                let mut used = self.used.lock().unwrap();
                if !*used {
                    *used = true;
                    return HookAction::ContinueWithMessage("continue".to_string());
                }
            }
            HookAction::Continue
        }
    }

    struct AlwaysContinueTurnEndHook;

    #[async_trait]
    impl HookHandler for AlwaysContinueTurnEndHook {
        async fn on_tool_event(&self, ctx: &ToolHookContext) -> HookAction {
            if ctx.event == HookEvent::TurnEnd {
                return HookAction::ContinueWithMessage("continue".to_string());
            }
            HookAction::Continue
        }
    }

    fn make_agent_record() -> Arc<AgentRecord> {
        Arc::new(AgentRecord {
            id: AgentId::new(1),
            display_name: "Test Agent".to_string(),
            description: "A test agent".to_string(),
            version: "1.0.0".to_string(),
            provider_id: Some(ProviderId::new(1)),
            model_id: None,
            system_prompt: "You are a test agent.".to_string(),
            tool_names: vec![],
            max_tokens: None,
            temperature: None,
            thinking_config: None,
            parent_agent_id: None,
            agent_type: AgentType::Standard,
        })
    }

    fn make_turn(
        provider: Arc<dyn LlmProvider>,
        hooks: Vec<Arc<dyn HookHandler>>,
        max_iterations: u32,
    ) -> Turn {
        let (stream_tx, _stream_rx): (broadcast::Sender<TurnStreamEvent>, _) =
            broadcast::channel(256);
        let (thread_event_tx, _thread_event_rx): (broadcast::Sender<ThreadEvent>, _) =
            broadcast::channel(256);

        TurnBuilder::default()
            .turn_number(1)
            .thread_id("thread-test".to_string())
            .messages(vec![ChatMessage::user("start")])
            .provider(provider)
            .hooks(hooks)
            .config(TurnConfig {
                max_iterations: Some(max_iterations),
                ..TurnConfig::default()
            })
            .agent_record(make_agent_record())
            .stream_tx(stream_tx)
            .thread_event_tx(thread_event_tx)
            .build()
            .expect("turn should build")
    }

    #[tokio::test]
    async fn turn_end_continue_with_message_triggers_next_iteration() {
        let provider = Arc::new(SequencedProvider::new(vec![
            CompletionResponse {
                content: Some("first".to_string()),
                reasoning_content: None,
                tool_calls: Vec::new(),
                input_tokens: 1,
                output_tokens: 1,
                finish_reason: FinishReason::Stop,
                cache_read_input_tokens: 0,
                cache_creation_input_tokens: 0,
            },
            CompletionResponse {
                content: Some("second".to_string()),
                reasoning_content: None,
                tool_calls: Vec::new(),
                input_tokens: 1,
                output_tokens: 1,
                finish_reason: FinishReason::Stop,
                cache_read_input_tokens: 0,
                cache_creation_input_tokens: 0,
            },
        ]));

        let turn = make_turn(provider, vec![Arc::new(ContinueOnceTurnEndHook::new())], 5);
        let output = turn.execute().await.expect("turn should succeed");

        assert!(
            output
                .appended_messages
                .iter()
                .any(|m| m.content == "first")
        );
        assert!(
            output
                .appended_messages
                .iter()
                .any(|m| m.content == "continue")
        );
        assert!(
            output
                .appended_messages
                .iter()
                .any(|m| m.content == "second")
        );
    }

    #[tokio::test]
    async fn turn_end_always_continue_hits_max_iterations() {
        let provider = Arc::new(SequencedProvider::new(vec![CompletionResponse {
            content: Some("loop".to_string()),
            reasoning_content: None,
            tool_calls: Vec::new(),
            input_tokens: 1,
            output_tokens: 1,
            finish_reason: FinishReason::Stop,
            cache_read_input_tokens: 0,
            cache_creation_input_tokens: 0,
        }]));

        let turn = make_turn(provider, vec![Arc::new(AlwaysContinueTurnEndHook)], 2);
        let result = turn.execute().await;

        assert!(matches!(result, Err(TurnError::MaxIterationsReached(2))));
    }
}
