use std::env;
use std::fs;
use std::path::Path;

#[path = "build_support/http_insecure_ssl_whitelist.rs"]
mod http_insecure_ssl_whitelist;

const CONFIG_RELATIVE_PATH: &str = "config/http-insecure-ssl-suffixes.txt";

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set");
    let workspace_root = Path::new(&manifest_dir)
        .parent()
        .and_then(|path| path.parent())
        .expect("argus-tool should live under crates/ within the workspace");
    let config_path = workspace_root.join(CONFIG_RELATIVE_PATH);
    let config_contents = if config_path.exists() {
        fs::read_to_string(&config_path)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", config_path.display()))
    } else {
        String::new()
    };

    let suffixes = http_insecure_ssl_whitelist::parse_insecure_ssl_suffixes(&config_contents)
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", config_path.display()));

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR must be set");
    let generated_path = Path::new(&out_dir).join("generated_http_insecure_ssl_suffixes.rs");
    let generated = render_generated_module(&suffixes);
    fs::write(&generated_path, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", generated_path.display()));

    println!("cargo:rerun-if-changed={}", config_path.display());
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=build_support/http_insecure_ssl_whitelist.rs");
}

fn render_generated_module(suffixes: &[String]) -> String {
    let mut rendered = String::from(
        "// WARNING: This file is auto-generated by build.rs\n\
         // Do not edit manually\n\n\
         pub const INSECURE_SSL_SUFFIX_WHITELIST: &[&str] = &[\n",
    );

    for suffix in suffixes {
        rendered.push_str(&format!("    {:?},\n", suffix));
    }

    rendered.push_str("];\n");
    rendered
}
